### ISSUE TITLE
How do you pronounce sqflite?

### ISSUE THREAD

**Issue by apaatsio** [tekartik/sqflite#100]
S-Q-flite? S-Q-F-lite? Sequeflite?

**Comment by alextekartik** [comment]
Funny question. I’m pretty bad at naming things (sqflite, tekartik, sembast are good examples of why you should never hire me to give a cool name easy to pronounce and remember for your project). Being non-native english speaker, I will certainly not give a lesson on how to pronounce it. Being french lowers even more my ability to pronounce it properly (I still don’t pronounce SQL the sequel way). And since I did the coding without talking out loud. I don’t think I ever said the name orally.
But since you ask, It seems I say in my head “S-Q-flite”, keeping the ‘FL’ effect of Flutter but I like the trendy ‘sequeflite’ which makes it sound like if we have 15 years of experience on it!
Cheers and I will use your recommendation!

**Comment by apaatsio** [comment]
Thanks for the answer!
