### ISSUE TITLE
Delete all rows

### ISSUE THREAD

**Issue by dark-chocolate** [tekartik/sqflite#112]
Is there any way to delete all the rows from the Table?
Like in Android you can use

`db.detete("TABLE_NAME", null, null);
`

As of now, I am using for loop to do that work and I was thinking of some inbuilt call to do that. Does anyone have an idea how to do it?

**Comment by alextekartik** [comment]
See https://github.com/tekartik/sqflite/issues/69

In general, the API is largely based on the Android API so actually `db.delete(tableName)` should do what you want in dart as well!

For generic SQLite usage and question, you could consider using StackOverflow instead of a github issue (which is more intended for reporting...issues). Documentation is a known issue but sqlite.org website has most of the documentation regarding SQL commands (See `DELETE` explanation here: https://www.sqlite.org/lang_delete.html)

**Comment by dark-chocolate** [comment]
Sorry I am new to Github and next time I will post on Stackoverflow. And thanks for your answer.

**Comment by alextekartik** [comment]
No problem @dark-chocolate The good thing about stackoverflow is that you reach a bigger community and your question might help others.
