### ISSUE TITLE
[sqflite_common_ffi_web] service worker not loading

### ISSUE THREAD

**Issue by jimmyff** [tekartik/sqflite#1145]
Hey, thanks for this awesome package. I'm moving over from using sqlite3 package and this takes a lot of the sharp edges away, the async stuff is a game changer -thanks for all the work!

I'm a little difficulty getting the experimental web package (`sqflite_common_ffi_web`) working, it seems that the server workers file (`sqflite_sw.js`) isn't actually loading in the browser, it's status in the inspector shows as (pending):

![Screenshot 2024-11-19 at 17 42 30](https://github.com/user-attachments/assets/6865c5fc-a4e6-4fe1-a1d7-ca6c90885493)

Just wondered if you've seen this before and if so could point me in a direction?

Thanks very much,
Jimmy

**Comment by alextekartik** [comment]
Did you run the setup script: https://github.com/tekartik/sqflite/tree/master/packages_web/sqflite_common_ffi_web#setup

```bash
$ dart run sqflite_common_ffi_web:setup
```

**Comment by jimmyff** [comment]
Hey @alextekartik - sorry I should I have clarified that, yeah I ran the setup script and also when I open the service worker URL directly it successfully loads the JS: `(function dartProgram(){func...`. 

You can actually see the deployment [here](https://hq.popsnap.app/). 

I noticed the web example project has a `sw.dart` file app entrypoint however I haven't tried including that as it's not mentioned in the readme?

Thanks

**Comment by alextekartik** [comment]
There is a similar issue here where it was fixed using uncorrelated mime types (that I don't fully understand but it seems to be needed for some hosting): https://github.com/tekartik/sqflite/issues/1043#issuecomment-1708391006

i.e. is the sqlite3.wasm properly loaded in the worker?

If you look and the raw example here: https://github.com/alextekartik/flutter_app_example/tree/master/demo_sqflite

It is online here: https://tk-demo-sqflite.web.app/

sqflite_sw.js has the same pending status (i guess because it is a shared worker) although it does work. Maybe you can try the simple demo app on your hosting to see if it works.

> I noticed the web example project has a sw.dart file app entrypoint however I haven't tried including that as it's not mentioned in the readme?

Now it is only a test to use a different service worker name. Not needed.

Also check your db path for the web (Can you try it to be a simple name - no full path) - maybe print it in the logs when if fails.

**Comment by alextekartik** [comment]
Well the mime type does not seem to be the issue:
```shell
$ curl -I https://tk-demo-sqflite.web.app/sqlite3.wasm
content-type: application/wasm
$ curl -I https://hq.popsnap.app/sqlite3.wasm
content-type: application/wasm
```

Can you tell the dbName you are using?

**Comment by jimmyff** [comment]
Apologies I've fixed the issue. It was actually a problem loading the content to populate the database with that was getting caught in the database initialising code.

Thanks for the help  🙏
