### ISSUE TITLE
Proper documentation for total beginners

### ISSUE THREAD

**Issue by PhilParisot** [tekartik/sqflite#122]
Proper documentation that explains all the functions in detail would go miles to help total beginners who haven't touched SQLite in the past or mobile development (which is my case).

I'm lucky enough to be a senior student in computer science and it's still quite tough for me, I can't image how difficult it could be for a complete novice.

Thanks!

**Comment by dlpigpen** [comment]
@SocialMammoth i think so. I am trying to understand each part to part and order them sequentially. It is quite difficult for a beginner using this library.

**Comment by Mohammed90** [comment]
Check [here](https://github.com/tekartik/sqflite/blob/master/doc/how_to.md) and (here)[https://pub.dartlang.org/documentation/sqflite/latest/].

**Comment by alextekartik** [comment]
Thanks for the note.

More documentation is always welcome. I'm doing this in my free time and as a non-english speaker I'm not the best candidate to write such documentation so contribution is welcome (even from newbies since they can explain in which area they needed help).

Explaining SQLite is even harder but there are tons of Android tutorial on that that could help. There are also some blog and medium posts tackling flutter and sqflite that are good read.

Since I don't have a proper resolution for this issue as of now and in the short term, what I can suggest is that I can create a doc section with some relevant links (tutorials, sample projects) that users can contribute too (by PR or posting links in this issue).

**Comment by SocialMammoth** [comment]
@alextekartik That would be an awesome start. When we google online we never know if we're learning from a reliable source or some scrappy code (as beginners). A page with learning resources that the creator agrees with would help enormously.

Thanks for the quick reply!

**Comment by 5ummit** [comment]
I agree that more documentation is needed but you can always search on youtube for starters here are 2 great examples which (if you have the patents for) can teach you the basics:
[https://youtu.be/Yzfxqd9-6QY](https://youtu.be/Yzfxqd9-6QY)
[https://youtu.be/zEqH2qYs7Pg](https://youtu.be/zEqH2qYs7Pg)

Hope this helps.

**Comment by alextekartik** [comment]
Thanks for your suggestion, I started a document here with your links: <https://github.com/tekartik/sqflite/blob/master/doc/external.md> with hopefully more content in the near future.

Regarding your last question 'If there was a way to have that documentation outside of the editor?'  yes, the inline documentation is also available from here: <https://pub.dartlang.org/documentation/sqflite/latest/>
