### ISSUE TITLE
About Read-only

### ISSUE THREAD

**Issue by Thomson-Tsui** [tekartik/sqflite#140]
I got the result "List<Map>" When i execute ".rawQuery" method. Now , i need to add a new kay-value to map which in result, the console told me "Unsupported operation: read-only", what should i do to edit the map in result? thanks.

**Comment by alextekartik** [comment]
Indeed the documentation was not clear that the results from a query is read-only. You need to create a new map in order to be able to modify it using for example `Map.from`. I added the following doc:

Assuming the following read results:

```dart
List<Map<String, dynamic>> records = await db.query('my_table');
```

Resulting map items are read-only

```dart
// get the first record
Map<String, dynamic> mapRead = records.first;
// Update it in memory...this will throw an exception
mapRead['my_column'] = 1;
// Crash... `mapRead` is read-only
```

You need to create a new map if you want to modify it in memory

```dart
// get the first record
Map<String, dynamic> map = Map<String, dynamic>.from(mapRead);
// Update it in memory now
map['my_column'] = 1;
```
