### ISSUE TITLE
Support SQLite 3.25.0

### ISSUE THREAD

**Issue by EmperorTigris** [tekartik/sqflite#149]
This was just fixed with 2018-09-15 (3.25.0)

Enhancements the ALTER TABLE command:

Add support for renaming columns within a table using ALTER TABLE table RENAME COLUMN oldname TO newname.
Fix table rename feature so that it also updates references to the renamed table in triggers and views.

Important if we want to rename column names.

**Comment by alextekartik** [comment]
Since sqflite uses whatever sqlite the platform provides, it is not possible to change it. The alternative solution would along the line of what is done in https://github.com/QwilApp/encrypted_sqlite by bundling sqlite binaries for each platform and architecture which is not currently the scope of this package.

**Comment by EmperorTigris** [comment]
Thanks for letting me know.
