### ISSUE TITLE
How to do a SELECT query using WHERE IN?

### ISSUE THREAD

**Issue by silverAndroid** [tekartik/sqflite#15]
Does sqflite support using WHERE...IN? Because when I try 
```dart
// Tried both IN (?) and IN ? with 1st argument of whereArgs as array and string
db.query('table', where: 'id IN (?)', whereArgs: [ids.join(', ')], orderBy: 'id ASC');
```
it returns 0 rows, which means it's most likely not forming the query properly (although I'm not sure how I can see the complete query being sent), and I'm sure it's not the DB missing the data or writing the query wrong because when I did a query on the DB myself, it returned the rows I was looking for.

**Comment by alextekartik** [comment]
yes IN is supported, I posted an example here https://github.com/tekartik/sqflite/blob/master/example/lib/exp_test_page.dart#L67-L77

Two solutions for you 
* either you put the proper numbers of ? i.e. `where: 'id IN (?, ?, ?...?)'` and put the ids in an array in `whereArgs: ids`
* since its ids, assuming it is integer, you could do `where: 'id IN (${ids.join(', ')})'`

**Comment by silverAndroid** [comment]
Thanks!

**Comment by josebraz** [comment]
If you query for strings: `where: 'id IN (${strings.map((e) => "'$e'").join(', ')})'`

**Comment by marcosalberto1991** [comment]
tuve problemas en solucionar pero me llevo un tiempo
sqflite: ^1.3.0+3

`where: 'idDb IN (${user.map((e) => "?").join(', ')})',
`
`List<int> user = [ 2,3,5,9 ];
` 

List<Map> maps = await dbClient.query(
      'programacionInspeccion',
      columns: ['*'],
      where: 'idDb IN (${user.map((e) => "?").join(', ')})',
      orderBy: 'fechaInicial ASC ',
      whereArgs: user,

    );
