### ISSUE TITLE
Question: is there a way to set the encoding of the text fields.

### ISSUE THREAD

**Issue by talamaska** [tekartik/sqflite#150]
I'm having issues with some french accents. So wondering if this is something provoked by wrong db encoding or flutter encoding, or even http request encoding?

**Comment by alextekartik** [comment]
I have not played much with this yet to have a good response. I know there is a way to force sqlite encoding (https://www.sqlite.org/pragma.html#pragma_encoding) and I know that existing db can have their encoding different, otherwise I would assume utf8 is the default. Good if you can define which issues you encounter (some test I could run?) so I can take a look

**Comment by talamaska** [comment]
Issue is resolved, turned out its the http from dart:io and the server is not sending charset. Did manual deciding on the bodybytes

**Comment by bilaloz** [comment]
how can you tell @talamaska

**Comment by talamaska** [comment]
I just assumed utf8
