### ISSUE TITLE
Support for Spatialite

### ISSUE THREAD

**Issue by synw** [tekartik/sqflite#156]
Is there any chance to get support for Spatialite, the geospacial database version of Sqlite? I know it is supported in Android native code. 

It would be great to be able to perform geospacial queries on device with Flutter

**Comment by alextekartik** [comment]
Hi and thanks for your note.
Since sqflite uses whatever sqlite the platform provides, it is not possible to change it. The alternative solution would along the line of what is done in https://github.com/QwilApp/encrypted_sqlite by bundling sqlite/spatialite binaries for each platform and architecture which is not currently the scope of this package.

**Comment by synw** [comment]
Thanks for your quick response and the info. Unfortunately not knowing native coding I am not capable of working this out. If anyone is interested by a Spatialite for Flutter project I'll be glad to contribute where I can.

**Comment by lukepighetti** [comment]
Hello, I am running into a similar need. I am trying to get performant geospatial queries in a flutter app and there aren't many good fast options. Being able to use SpatiaLite would solve a lot of problems for us. I have time to look into solving this but I have no idea where to start. Can someone, maybe @alextekartik give me a little background info? Is it possible for `sqflite` to run on Android and iOS with SpatiaLite?
