### ISSUE TITLE
Does it support SQLITE COLLATE ?

### ISSUE THREAD

**Issue by pravinarr** [tekartik/sqflite#157]
I am trying to search a columns which has diacritics in it. So does SQFLite support "SELECT" with "COLLATE NOACCENTS"?

If yes, can you share an example for it ?

**Comment by alextekartik** [comment]
Since sqflite uses whatever sqlite the platform provides, it would depend on whatever existing iOS and Android. As far as I know this is not supported on Android but I could be wrong. One suggestion here https://stackoverflow.com/questions/26871674/sqlite-custom-accent-collation-function-and-like-queries#26874223 is to store a normalized form of the text in another column.

I guess stackoverflow would be a better friend here.

**Comment by pravinarr** [comment]
@alextekartik Thank you
