### ISSUE TITLE
Cookbook Error: Data loss on app upgrade

### ISSUE THREAD

**Issue by brianegan** [tekartik/sqflite#166]
Hey there -- first of all, amazing contribution to the community :) Thanks so much!

Now, onto the issue: this isn't something I've experienced myself, but I wrote a recipe for the Flutter cookbook that introduces folks to sqflite! However, one user has written in saying their database is lost on every upgrade.

Since the recipe demonstrates the `getDatabasePath` function, which returns the `databases` directory for your Android app, it seemed like that shouldn't be a problem. That said, I wanted to alert you to the issue and see if you had any idea why it might be happening?

https://github.com/flutter/website/issues/2443

**Comment by alextekartik** [comment]
Thansk for the note. I am note aware of such issue (and nobody reported this although there are applicationd on PlayStore using sqflite). I will try to have @kw2019ltd describe it here rather than in the flutter/website issue

@kw2019ltd can you describe:
- your database location path
- whether the database has the same version/schema/code before and after the update
- whether it was tested using the release version the app (i.e. same application id and signature)
- how I could reproduce the issue

thanks!

**Comment by brianegan** [comment]
Excellent, thanks again!

**Comment by alextekartik** [comment]
source bug closed (no news)
