### ISSUE TITLE
[iOS] Database operation is blocking the UI thread

### ISSUE THREAD

**Issue by simpleliujl** [tekartik/sqflite#174]
A Flutter plugin receives messages on the UI thread, while the [FMDatabaseQueue inDatabase:] performs the query on the thread where it is invoked。

See [FMDatabaseQueue is Blocking the main thread. #436](https://github.com/ccgus/fmdb/issues/436)。

**Comment by alextekartik** [comment]
Thanks for the report and the pointer. I'm not an iOS expert and in my first fmdb reading my assumption was that `inDatabase` was synchronizing calls in a background thread. It seems I was wrong. I do most of the development on Linux/Android (here I know we are running in a background thread) so I guess I don't give iOS the attention it deserves. In my initial tests on iOS (couple of years ago), flutter services were crashing when not ran in the UI thread. I hope this has changed (i.e. I hope I can send the result back from the background thread).

So it seems I should do something like:

```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
    [database.fmDatabaseQueue inDatabase:^(FMDatabase *db) {
        // ... query/insert/update/delete
    });
});
```

for each call. Am I correct? I'm not sure how to efficiently test this so inputs are welcome. Also a review of my iOS code would be welcome

**Comment by simpleliujl** [comment]
I think wrapping each FMDB call with

```objc
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
// FMDB calls
});
```
and dispatching the `result` callback to the main thread will solve the problem.

```objc
dispatch_async(dispatch_get_main_queue(), ^{
    result(@(YES));
});
```

**Comment by alextekartik** [comment]
Thanks for the PR! Weird that nobody reported that before. I guess it means that SQLite is really fast. I published version 1.1.4-dev.1 (so that it is available but it gives me some time to test in some of my applications especially in some new isolate scenarios).

Some questions where you might help:
- All db operations (not open/close database yet) happens in one thread with priority DISPATCH_QUEUE_PRIORITY_DEFAULT. Is it adequate or should we give it a lower priority? (on Android I did put a lower priority)
- When using multiple db, they share the same global queue. Would it be better to create one queue per database?. I tried using `dispatch_queue_create` but could not found a way to set the priority.
- I'm still not sure whether we need to send the result back in the main thread. I think no so I might remove the dispatch wrapper (wrappedResult) in the future. If yes, there is the isolate scenario I tackled recently (yes sql can run from an isolate and here the method are called already in a separate thread - see https://github.com/tekartik/sqflite/issues/168). In this case, the wrapper should not dispatch in the main queue but in the current caller thread queue. What would the wrappedResult code would be in this case to dispatch in the original thread?

Thanks again!

**Comment by simpleliujl** [comment]
Thanks for your reply, I'm pleased to give a personal opinion on these questions.

For the first question, I think the *default* priority might be suitable for most scenarios as a default choice.  According to Apple’s document [Energy Efficiency Guide for iOS Apps](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html), there are four primary QoS classes (user-interactive, user-initiated, utility and background). A *default* priority falls between *user-initiated* and *utility*, while a background operation may be suspended when lower power mode is enabled.

For the second question, a global queue returned by `dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)` is underlying backed by several worker threads, and it could perform database operations concurrently. Meanwhile, the `fmDatabaseQueue` created by FMDB for each database connection is a serial queue, which acts just like a lock and helps coordinate database operations from different threads.

For the third question, I am not sure whether the `result` callback should be invoked in the main thread. I've tested with [flutter_isolate](https://github.com/rmawatson/flutter_isolate) and it appears that the plugin still receives method calls in UI thread. Maybe I should dive into the flutter engine's source code for more information.

Hope this helps!

**Comment by alextekartik** [comment]
Your opinion are very helpful to me. So it seems that currently your modification solved perfectly the issue you were seeing and should remain as is! Thanks again. The next improvment I see could be to open/close the database in a background but that sounds less important (in my use case, I open the database at the beginning after displaying something and never close the database).
