### ISSUE TITLE
Nested Maps/Json are not fetched in a correct JSON format 

### ISSUE THREAD

**Issue by michalorestes** [tekartik/sqflite#179]
Hi team, 

I am using sqdlite with flutter. 

I have a object that contains other objects, therefore I wrote toJson/fromJson functions for all objects to create a valid JSON using maps. 

However, I am unable to convert data fetched from DB to the original object because somehow SqfLite changes the structure of JSON data at the time of storing to DB or reading from. 

To illustrate, right before calling 
`transaction.insert("exercise", e.toJson());`

The structure looks like this (have a look at the nested object "muscleGroups"): 

```
{
   name:Bench Press,
   exerciseType:2,
   muscleGroups:{
      primaryGroup:3,
      secondaryGroups:2
   },
   isCustom:false,
   availableLoggingTypes:1,
   defaultLoggingType:1,
   id:0
}

```
However, once the data is fetched, it looks like this (check the muscleGroups object): 

```
{
   id:0,
   name:Bench Press,
   exerciseType:2,
   muscleGroups:{
      secondaryGroups=dd,
      primaryGroup=3
   },
   isCustom:0,
   availableLoggingTypes:1,
   defaultLoggingType:1
}

```

For some reason, colons were replaced with equals sign. 

I am not sure if there is a bug or if it's simply me doing something wrong. However, I couldn't find any releated bugs reported or resources showing how to implement nested objects, although it should be relatively simple. Could you please assist me with this issue? I've included all relevant code below: 

**Exercise Model:** 
```
class Exercise {
  int id;
  String name;
  ExerciseType exerciseType;
  MuscleGroups muscleGroups;
  bool isCustom;
  List<ExerciseLoggingType> availableLoggingTypes;
  ExerciseLoggingType defaultLoggingType;

  String get type => exerciseType.toString().split(".")[1];

  Exercise(
      {this.id,
      this.name,
      this.exerciseType,
      this.muscleGroups,
      this.isCustom,
      this.availableLoggingTypes,
      this.defaultLoggingType});

  String getIconAsset() {
    return "assets/sample_exercise_icon.png";
  }

  Map<String, dynamic> toJson() {
    print(this.muscleGroups);
    Map<String, dynamic> map = {
      "name": name,
      "exerciseType": exerciseType.index,
      "muscleGroups": muscleGroups.toJson(),
      "isCustom": isCustom,
      "availableLoggingTypes": availableLoggingTypes.map((ExerciseLoggingType type) => type.index).join(","),
      "defaultLoggingType": defaultLoggingType.index
    };

    if (id != null) {
      map['id'] = id;
    }

    return map; 
  }

  static Exercise fromJson(Map<String, dynamic> json) {
    print(json['muscleGroups']);
    return Exercise(
      id: json['id'],
      name: json['name'],
      exerciseType: ExerciseType.values[int.parse(json['exerciseType'])],
      muscleGroups: MuscleGroups.fromJson(JSON.jsonDecode(json['muscleGroups'])),
      isCustom: json['isCustom'],
      defaultLoggingType: ExerciseLoggingType.values[json['defaultLoggingType']],
      availableLoggingTypes: json['availableLoggingTypes']
                              .toString()
                              .split(",")
                              .map((dynamic type) => ExerciseLoggingType.values[type])
                              .toList(),
    );
  }

  static Future<List<Exercise>> fetchAllExercises() async {
    final db = await DatabaseProvider.database; 
    List<Map<String, dynamic>> result = await db.query("exercise");
    List<Exercise> data = List(); 
    result.forEach((Map<String, dynamic> row) => data.add(Exercise.fromJson(row))); 
    
    return data; 
  }

  Future<int> save() async {
    final db = await DatabaseProvider.database; 
    var j = this.toJson(); 
    print(j);
    return db.insert("exercise", this.toJson());
  }
}
```

**MuscleGroups model**
```
class MuscleGroups {
  MuscleGroupsType primaryGroup;
  List<MuscleGroupsType> secondaryGroups;

  String get primary => primaryGroup.toString().split(".")[1];

  MuscleGroups({this.primaryGroup, this.secondaryGroups});

  Map<String, dynamic> toJson() {
    Map<String, dynamic> map = {
      "primaryGroup": primaryGroup.index,
      "secondaryGroups": "dd"
    };

    return map;
  }

  static MuscleGroups fromJson(Map<String, dynamic> json) {
    List<MuscleGroupsType> list = json['secondaryGroups']
                        .toString()
                        .split(",")
                        .map((dynamic enumIndex) => MuscleGroupsType.values[enumIndex])
                        .toList();
   
    return MuscleGroups(
      primaryGroup: MuscleGroupsType.values[int.parse(json['primaryGroup'])],
      secondaryGroups: list
    );
  }
}
```

**This is how I am creating the DB:** 

```
class DatabaseProvider {
  static Database _database;

  DatabaseProvider._();

  static Future<Database> get database async {
    if (_database != null) {
      return _database;
    }

    _database = await _initDB();

    return _database;
  }

  static Future<Database> _initDB() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, "TestDB.db");

    await deleteDatabase(path);
    Database database = await openDatabase(path, version: 3, onOpen: (db) {},
        onCreate: (Database db, int version) async {
      await db.execute("CREATE TABLE workout ("
          "id INTEGER PRIMARY KEY,"
          "name TEXT,"
          "type TEXT,"
          "schedule TEXT"
          ")");

      await db.execute("CREATE TABLE exercise ("
          "id INTEGER PRIMARY KEY,"
          "name TEXT,"
          "exerciseType TEXT,"
          "muscleGroups TEXT,"
          "isCustom TEXT,"
          "availableLoggingTypes TEXT,"
          "defaultLoggingType TEXT"
          ")");
    });

    await database.transaction((Transaction transaction) async {
      Exercise e = Exercise(
        name: "Bench Press",
        isCustom: false,
        defaultLoggingType: ExerciseLoggingType.REPS,
        availableLoggingTypes: [ExerciseLoggingType.REPS],
        exerciseType: ExerciseType.WEIGHTS,
        muscleGroups: MuscleGroups(
          primaryGroup: MuscleGroupsType.CHEST,
          secondaryGroups: [MuscleGroupsType.TRICEPS],
        ),
      );

      Workout w = Workout(
        name: "Workout A",
        type: WorkoutTypes.WEIGHTS,
        schedule: ["monday"],
      );

      transaction.insert("workout", w.toJson());
      transaction.insert("exercise", e.toJson());
    });

    return database;
  }
}

```

**Comment by alextekartik** [comment]
Column content cannot be a map. It can only be one of the type listed here: https://pub.dartlang.org/packages/sqflite#supported-sqlite-types. Here the map is converted to a string.
In your case you could either flatten the hierarchy or use `json.encode/decode` to save the `muscleGroups` field

**Comment by michalorestes** [comment]
Thanks @alextekartik  for your reply. 
I've ended up flattening my structure. 
I don't know what got me in to treating this like mongo db lol.

**Comment by Bryanmuloni** [comment]
Hi @michalorestes how do I flatten my structure, I am going through the same issue. An example will be much appreciated. Thanks

**Comment by alextekartik** [comment]
@Bryanmuloni There is a super simple example for "flattening" here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/supported_types.md#supported-types

but basically if you have a hierarchy like:

```
field1
nested
  field2
  sub
    field3
    field4
```

You should bring all fields to the top level:
```
field1
nestedField2
nestedSubField3
nestedSubField4
```

As a note, it does not work easily with sublist....

**Comment by Bryanmuloni** [comment]
@alextekartik thank you for your response. Here is my model class, guide me accordingly.
class SurveyEntry {
  int surveyId;
  String surveyStatus;
  SectionOneEntry sectionOneEntry;
  SectionTwoEntry sectionTwoEntry;
  SectionThreeEntry sectionThreeEntry;
  SectionFourEntry sectionFourEntry;
  SectionFiveEntry sectionFiveEntry;
  SectionSixEntry sectionSixEntry;

  SurveyEntry(
      {this.surveyStatus,
      this.sectionOneEntry,
      this.sectionTwoEntry,
      this.sectionThreeEntry,
      this.sectionFourEntry,
      this.sectionFiveEntry,
      this.sectionSixEntry});

  SurveyEntry.surveyEntryWithId(
      {this.surveyId,
      this.surveyStatus,
      this.sectionOneEntry,
      this.sectionTwoEntry,
      this.sectionThreeEntry,
      this.sectionFourEntry,
      this.sectionFiveEntry,
      this.sectionSixEntry});

  factory SurveyEntry.empty() {
    return SurveyEntry.surveyEntryWithId(
        surveyId: null,
        surveyStatus: null,
        sectionOneEntry: null,
        sectionTwoEntry: null,
        sectionThreeEntry: null,
        sectionFourEntry: null,
        sectionFiveEntry: null,
        sectionSixEntry: null);
  }

  Map<String, dynamic> surveyToJson() => _surveyToJsonConversion(this);

  factory SurveyEntry.surveyFromJson(Map<String, dynamic> surveyMap) {
    return SurveyEntry.surveyEntryWithId(
        surveyId: surveyMap["id"],
        surveyStatus: surveyMap["status"],
        sectionOneEntry: SectionOneEntry.sectionOneFromJson(surveyMap["one"]),
        sectionTwoEntry: SectionTwoEntry.sectionTwoFromJson(surveyMap["two"]),
        sectionThreeEntry: SectionThreeEntry.sectionThreeFromJson(surveyMap["three"]),
        sectionFourEntry: SectionFourEntry.sectionFourFromJson(surveyMap["four"]),
        sectionFiveEntry: SectionFiveEntry.sectionFiveFromJson(surveyMap["five"]),
        sectionSixEntry: SectionSixEntry.sectionSixFromJson(surveyMap["six"]));
  }
}

Map<String, dynamic> _surveyToJsonConversion(SurveyEntry surveyEntry) {
  Map<String, dynamic> surveyMap = Map<String, dynamic>();
  if (surveyEntry?.surveyId != null) {
    surveyMap["id"] = surveyEntry.surveyId;
  }
  surveyMap["status"] = surveyEntry.surveyStatus;
  surveyMap["one"] = _sectionOneToJson(surveyEntry.sectionOneEntry);
  surveyMap["two"] = _sectionTwoToJson(surveyEntry.sectionTwoEntry);
  surveyMap["three"] = _sectionThreeToJson(surveyEntry.sectionThreeEntry);
  surveyMap["four"] = _sectionFourToJson(surveyEntry.sectionFourEntry);
  surveyMap["five"] = _sectionFiveToJson(surveyEntry.sectionFiveEntry);
  surveyMap["six"] = _sectionSixToJson(surveyEntry.sectionSixEntry);
  return surveyMap;
}

SectionOneEntry _sectionOneFromJson(Map<String, dynamic> json) {
  SectionOneEntry sectionOneEntry = SectionOneEntry.sectionOneFromJson(json);
  return sectionOneEntry;
}

Map<String, dynamic> _sectionOneToJson(SectionOneEntry sectionOneEntry) {
  if (sectionOneEntry == null) {
    return null;
  }
  Map<String, dynamic> sectionOneMap = jsonEncode(sectionOneEntry) as Map<String, dynamic>;
  // sectionOneMap = sectionOneEntry.sectionOneToJson();
  return sectionOneMap;
}

SectionTwoEntry _sectionTwoFromJson(Map<String, dynamic> json) {
  SectionTwoEntry sectionTwoEntry = SectionTwoEntry.sectionTwoFromJson(json);
  return sectionTwoEntry;
}

Map<String, dynamic> _sectionTwoToJson(SectionTwoEntry sectionTwoEntry) {
  if (sectionTwoEntry == null) {
    return null;
  }
  Map<String, dynamic> sectionTwoMap = Map<String, dynamic>();
  sectionTwoMap = sectionTwoEntry.sectionTwoToJson();
  return sectionTwoMap;
}

SectionThreeEntry _sectionThreeFromJson(Map<String, dynamic> json) {
  SectionThreeEntry sectionThreeEntry = SectionThreeEntry.sectionThreeFromJson(json);
  return sectionThreeEntry;
}

Map<String, dynamic> _sectionThreeToJson(SectionThreeEntry sectionThreeEntry) {
  if (sectionThreeEntry == null) {
    return null;
  }
  Map<String, dynamic> sectionThreeMap = Map<String, dynamic>();
  sectionThreeMap = sectionThreeEntry.sectionThreeToJson();
  return sectionThreeMap;
}

SectionFourEntry _sectionFourFromJson(Map<String, dynamic> json) {
  SectionFourEntry sectionFourEntry = SectionFourEntry.sectionFourFromJson(json);
  return sectionFourEntry;
}

Map<String, dynamic> _sectionFourToJson(SectionFourEntry sectionFourEntry) {
  if (sectionFourEntry == null) {
    return null;
  }
  Map<String, dynamic> sectionFourMap = Map<String, dynamic>();
  sectionFourMap = sectionFourEntry.sectionFourToJson();
  return sectionFourMap;
}

SectionFiveEntry _sectionFiveFromJson(Map<String, dynamic> json) {
  SectionFiveEntry sectionFiveEntry = SectionFiveEntry.sectionFiveFromJson(json);
  return sectionFiveEntry;
}

Map<String, dynamic> _sectionFiveToJson(SectionFiveEntry sectionFiveEntry) {
  if (sectionFiveEntry == null) {
    return null;
  }
  Map<String, dynamic> sectionFiveMap = Map<String, dynamic>();
  sectionFiveMap = sectionFiveEntry.sectionFiveToJson();
  return sectionFiveMap;
}

SectionSixEntry _sectionSixFromJson(Map<String, dynamic> json) {
  SectionSixEntry sectionSixEntry = SectionSixEntry.sectionSixFromJson(json);
  return sectionSixEntry;
}

Map<String, dynamic> _sectionSixToJson(SectionSixEntry sectionSixEntry) {
  if (sectionSixEntry == null) {
    return null;
  }
  Map<String, dynamic> sectionFiveMap = Map<String, dynamic>();
  sectionFiveMap = sectionSixEntry.sectionSixToJson();
  return sectionFiveMap;
}

**Comment by alextekartik** [comment]
If you don't plan to have any `WHERE` clause on any field, one solution is to have a single column `data TEXT` where you can put the json encoded content.

That is said having data one, two, three (which is typically for no sql database) can be modified with SQL to have for example a `Survey` table and a `SurveyEntry` table, each survey entry table having a pointer in the survey table.

But of course it depends on how you get the model (I guess from a REST API) so in this case, just put the raw json in a text column should be sufficient. As a note this is not specific to sqflite, you might be able to get help from stack overflow regarding how to use SQLite.

(please enclose your code with triple ticks for better formatting as plain code text is difficult to read)

**Comment by Bryanmuloni** [comment]
Thank you so much @alextekartik for the guidance, flattening my structure(Switched objects with respective fields) as below worked like a charm. With this, I can now perform any operation on the table. With the good practice of adding comments, I have done so to ease code reading. Putting this here to guide others next time.
/// Survey data model
class SurveyEntry {
  // Unique Identifier for  each survey
  int surveyId;
  String surveyStatus;

  // Section one fields
  String memberName;
  String memberTitle;
  String associationName;
  String parishName;
  String villageName;
  String saccoName;
  String district;
  String constituency;
  String gender;
  String groupSize;

  // Section two fields
  String savingOption;
  String savingInterval;
  String savingAmount;
  String noSavingReason;

  // Section three fields
  String amountApplied;
  String amountGiven;
  String loanTerm;
  String loanDuration;
  String loanMaximum;
  String loanSecurityOption;
  String securityAccepted;
  String interestRate;
  String savingWithSacco;
  String savingWithAssoc;
  String assocMemberMeetOption;
  String meetingInterval;
  String meetingPlace;
  String noMeetingReason;
  String loanOfferToMemberOption;

  //Section four fields
  String amountSavedWithAssoc;
  String loanOfferOption;
  String numberOfMembers;
  String amountLoaned;
  String highestLoanSize;
  String impactOfLoans;

  //Section five fields
  String accessLoanOption;
  String loanPurpose;
  String noLoanAccessReason;
  String biggestHouseholdChallenge;

  //Section six fields
  String otherActivities;
  String challengesFacingOrFaced;
  String supportFromMSCOption;
  String kindOfSupport;
  String noMSCSupportReason;
  String mSCServiceSatisfactionOption;
  String noMSCServiceSatisfactionReason;

  /// Constructor to help insert a new survey, doesn't have an id since it is created automatically
  SurveyEntry(
      {this.surveyStatus,
      this.memberName,
      this.memberTitle,
      this.associationName,
      this.parishName,
      this.villageName,
      this.saccoName,
      this.district,
      this.constituency,
      this.gender,
      this.groupSize,
      this.savingOption,
      this.savingInterval,
      this.savingAmount,
      this.noSavingReason,
      this.amountApplied,
      this.amountGiven,
      this.loanTerm,
      this.loanDuration,
      this.loanMaximum,
      this.loanSecurityOption,
      this.securityAccepted,
      this.interestRate,
      this.savingWithSacco,
      this.savingWithAssoc,
      this.assocMemberMeetOption,
      this.meetingInterval,
      this.meetingPlace,
      this.noMeetingReason,
      this.loanOfferToMemberOption,
      this.amountSavedWithAssoc,
      this.loanOfferOption,
      this.numberOfMembers,
      this.amountLoaned,
      this.highestLoanSize,
      this.impactOfLoans,
      this.accessLoanOption,
      this.loanPurpose,
      this.noLoanAccessReason,
      this.biggestHouseholdChallenge,
      this.otherActivities,
      this.challengesFacingOrFaced,
      this.supportFromMSCOption,
      this.kindOfSupport,
      this.noMSCSupportReason,
      this.mSCServiceSatisfactionOption,
      this.noMSCServiceSatisfactionReason});

  /// Named constructor to help query from database since we need the id for further reference.
  SurveyEntry.surveyEntryWithId(
      {this.surveyId,
      this.surveyStatus,
      this.memberName,
      this.memberTitle,
      this.associationName,
      this.parishName,
      this.villageName,
      this.saccoName,
      this.district,
      this.constituency,
      this.gender,
      this.groupSize,
      this.savingOption,
      this.savingInterval,
      this.savingAmount,
      this.noSavingReason,
      this.amountApplied,
      this.amountGiven,
      this.loanTerm,
      this.loanDuration,
      this.loanMaximum,
      this.loanSecurityOption,
      this.securityAccepted,
      this.interestRate,
      this.savingWithSacco,
      this.savingWithAssoc,
      this.assocMemberMeetOption,
      this.meetingInterval,
      this.meetingPlace,
      this.noMeetingReason,
      this.loanOfferToMemberOption,
      this.amountSavedWithAssoc,
      this.loanOfferOption,
      this.numberOfMembers,
      this.amountLoaned,
      this.highestLoanSize,
      this.impactOfLoans,
      this.accessLoanOption,
      this.loanPurpose,
      this.noLoanAccessReason,
      this.biggestHouseholdChallenge,
      this.otherActivities,
      this.challengesFacingOrFaced,
      this.supportFromMSCOption,
      this.kindOfSupport,
      this.noMSCSupportReason,
      this.mSCServiceSatisfactionOption,
      this.noMSCServiceSatisfactionReason});

  /// Named empty constructor
  factory SurveyEntry.empty() {
    return SurveyEntry.surveyEntryWithId(
        surveyId: null,
        surveyStatus: null,
        memberName: null,
        memberTitle: null,
        associationName: null,
        parishName: null,
        villageName: null,
        saccoName: null,
        district: null,
        constituency: null,
        gender: null,
        groupSize: null,
        savingOption: null,
        savingInterval: null,
        savingAmount: null,
        noSavingReason: null,
        amountApplied: null,
        amountGiven: null,
        loanTerm: null,
        loanDuration: null,
        loanMaximum: null,
        loanSecurityOption: null,
        securityAccepted: null,
        interestRate: null,
        savingWithSacco: null,
        savingWithAssoc: null,
        assocMemberMeetOption: null,
        meetingInterval: null,
        meetingPlace: null,
        noMeetingReason: null,
        loanOfferToMemberOption: null,
        amountSavedWithAssoc: null,
        loanOfferOption: null,
        numberOfMembers: null,
        amountLoaned: null,
        highestLoanSize: null,
        impactOfLoans: null,
        accessLoanOption: null,
        loanPurpose: null,
        noLoanAccessReason: null,
        biggestHouseholdChallenge: null,
        otherActivities: null,
        challengesFacingOrFaced: null,
        supportFromMSCOption: null,
        kindOfSupport: null,
        noMSCSupportReason: null,
        mSCServiceSatisfactionOption: null,
        noMSCServiceSatisfactionReason: null);
  }

  Map<String, dynamic> surveyToJson() => _surveyToJsonConversion(this);

  /// Factory method to convert json data from database into class object
  factory SurveyEntry.surveyFromJson(Map<String, dynamic> surveyMap) {
    return SurveyEntry.surveyEntryWithId(
        surveyId: surveyMap["id"],
        surveyStatus: surveyMap["status"],
        memberName: surveyMap["member_name"],
        memberTitle: surveyMap["member_title"],
        associationName: surveyMap["association_name"],
        parishName: surveyMap["parish"],
        villageName: surveyMap["village"],
        saccoName: surveyMap["sacco"],
        district: surveyMap["district"],
        constituency: surveyMap["constituency"],
        gender: surveyMap["gender"],
        groupSize: surveyMap["group_size"],
        savingOption: surveyMap["saving_option"],
        savingInterval: surveyMap["saving_interval"],
        savingAmount: surveyMap["saving_amount"],
        noSavingReason: surveyMap["no_saving_reason"],
        amountApplied: surveyMap["amount_applied"],
        amountGiven: surveyMap["amount_given"],
        loanTerm: surveyMap["loan_term"],
        loanDuration: surveyMap["loan_duration"],
        loanMaximum: surveyMap["loan_max"],
        loanSecurityOption: surveyMap["loan_security_option"],
        securityAccepted: surveyMap["security_accepted"],
        interestRate: surveyMap["interest_rate"],
        savingWithSacco: surveyMap["sacco_saving"],
        savingWithAssoc: surveyMap["assoc_saving"],
        assocMemberMeetOption: surveyMap["meet_option"],
        meetingInterval: surveyMap["meeting_interval"],
        meetingPlace: surveyMap["meeting_place"],
        noMeetingReason: surveyMap["no_meeting_reason"],
        loanOfferToMemberOption: surveyMap["loan_offer_option"],
        amountSavedWithAssoc: surveyMap["assoc_amount_saved"],
        loanOfferOption: surveyMap["assoc_loan_offer_option"],
        numberOfMembers: surveyMap["number_of_members"],
        amountLoaned: surveyMap["assoc_amount_loaned"],
        highestLoanSize: surveyMap["loan_size"],
        impactOfLoans: surveyMap["loan_impact"],
        accessLoanOption: surveyMap["loan_access_option"],
        loanPurpose: surveyMap["loan_purpose"],
        noLoanAccessReason: surveyMap["no_loan_access_reason"],
        biggestHouseholdChallenge: surveyMap["household_challenge"],
        otherActivities: surveyMap["other_activity"],
        challengesFacingOrFaced: surveyMap["faced_challenge"],
        supportFromMSCOption: surveyMap["support_option"],
        kindOfSupport: surveyMap["support_kind"],
        noMSCSupportReason: surveyMap["no_support_reason"],
        mSCServiceSatisfactionOption: surveyMap["satisfaction_option"],
        noMSCServiceSatisfactionReason: surveyMap["no_satisfaction_reason"]);
  }
}

/// Utility method to convert class object data into json
Map<String, dynamic> _surveyToJsonConversion(SurveyEntry surveyEntry) {
  Map<String, dynamic> surveyMap = Map<String, dynamic>();
  if (surveyEntry?.surveyId != null) {
    surveyMap["id"] = surveyEntry.surveyId;
  }
  surveyMap["status"] = surveyEntry.surveyStatus;
  surveyMap["member_name"] = surveyEntry.memberName;
  surveyMap["member_title"] = surveyEntry.memberTitle;
  surveyMap["association_name"] = surveyEntry.associationName;
  surveyMap["parish"] = surveyEntry.parishName;
  surveyMap["village"] = surveyEntry.villageName;
  surveyMap["sacco"] = surveyEntry.saccoName;
  surveyMap["district"] = surveyEntry.district;
  surveyMap["constituency"] = surveyEntry.constituency;
  surveyMap["gender"] = surveyEntry.gender;
  surveyMap["group_size"] = surveyEntry.groupSize;
  surveyMap["saving_option"] = surveyEntry.savingOption;
  surveyMap["saving_interval"] = surveyEntry.savingInterval;
  surveyMap["saving_amount"] = surveyEntry.savingAmount;
  surveyMap["no_saving_reason"] = surveyEntry.noSavingReason;
  surveyMap["amount_applied"] = surveyEntry.amountApplied;
  surveyMap["amount_given"] = surveyEntry.amountGiven;
  surveyMap["loan_term"] = surveyEntry.loanTerm;
  surveyMap["loan_duration"] = surveyEntry.loanDuration;
  surveyMap["loan_max"] = surveyEntry.loanMaximum;
  surveyMap["loan_security_option"] = surveyEntry.loanSecurityOption;
  surveyMap["security_accepted"] = surveyEntry.securityAccepted;
  surveyMap["interest_rate"] = surveyEntry.interestRate;
  surveyMap["sacco_saving"] = surveyEntry.savingWithSacco;
  surveyMap["assoc_saving"] = surveyEntry.savingWithAssoc;
  surveyMap["meet_option"] = surveyEntry.assocMemberMeetOption;
  surveyMap["meeting_interval"] = surveyEntry.meetingInterval;
  surveyMap["meeting_place"] = surveyEntry.meetingPlace;
  surveyMap["no_meeting_reason"] = surveyEntry.noMeetingReason;
  surveyMap["loan_offer_option"] = surveyEntry.loanOfferOption;
  surveyMap["assoc_amount_saved"] = surveyEntry.amountSavedWithAssoc;
  surveyMap["assoc_loan_offer_option"] = surveyEntry.loanOfferOption;
  surveyMap["number_of_members"] = surveyEntry.numberOfMembers;
  surveyMap["assoc_amount_loaned"] = surveyEntry.amountLoaned;
  surveyMap["loan_size"] = surveyEntry.highestLoanSize;
  surveyMap["loan_impact"] = surveyEntry.impactOfLoans;
  surveyMap["loan_access_option"] = surveyEntry.accessLoanOption;
  surveyMap["loan_purpose"] = surveyEntry.loanPurpose;
  surveyMap["no_loan_access_reason"] = surveyEntry.noLoanAccessReason;
  surveyMap["household_challenge"] = surveyEntry.biggestHouseholdChallenge;
  surveyMap["other_activity"] = surveyEntry.otherActivities;
  surveyMap["faced_challenge"] = surveyEntry.challengesFacingOrFaced;
  surveyMap["support_option"] = surveyEntry.supportFromMSCOption;
  surveyMap["support_kind"] = surveyEntry.kindOfSupport;
  surveyMap["no_support_reason"] = surveyEntry.noMSCSupportReason;
  surveyMap["satisfaction_option"] = surveyEntry.mSCServiceSatisfactionOption;
  surveyMap["no_satisfaction_reason"] = surveyEntry.noMSCServiceSatisfactionReason;
  return surveyMap;
}
