### ISSUE TITLE
flutter-desktop-embeddin

### ISSUE THREAD

**Issue by allessandrosj** [tekartik/sqflite#194]
Any chance of sqflite support for flutter-desktop-embedding,
https://github.com/google/flutter-desktop-embedding

**Comment by alextekartik** [comment]
It would likely be a separate project but it should be feasible to have the same API and dart code and native binding to sql desktop libraries for each platform.

**Comment by stuartmorgan** [comment]
The desktop shells, including the plugin APIs, have moved into the Flutter engine itself, so the flutter-destkop-embedding project wouldn't actually come into it at all. Desktop implementations would use plugin APIs from the Flutter library, just as on mobile (although unlike mobile, those APIs aren't stable yet).

**Comment by stuartmorgan** [comment]
If you are interested in exploring desktop support, the macOS plugin APIs and tooling are in pretty good shape now, and it looks like you should be able to re-use pretty much all of your iOS code. The main differences would be:
- The framework is FlutterMacOS rather than Flutter
- You'd need a Swift wrapper around the plugin registration ([example](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/file_chooser/macos/Classes/FileChooserPlugin.swift))

If you try it out, I'd be interested in hearing how it works out for you.

**Comment by alextekartik** [comment]
Thanks @stuartmorgan for the note.

My initial hope was not to re-use but rather share code if possible. Having desktop support will make sense (I think) if we have the same API (i.e. if needed I can extract some common code in a new package). I'm still waiting to see how the flutter plugins will support desktop. `shared_preferences` and `path_provider` should be pretty easy. Will they need a new package or will the existing package support desktop? I don't want to make the wrong steps and create a new package to throw in a couple of weeks.

**Comment by xu4wang** [comment]
> Any chance of sqflite support for flutter-desktop-embedding,
> https://github.com/google/flutter-desktop-embedding

Sorry for off topic, Is there a place I can check which component is supported by flutter-desktop?

PS.
I am trying to run a flutter app on my MacOS book and facing the issue of sqflite  related exceptions.

**Comment by stuartmorgan** [comment]
> Sorry for off topic

Places for this question where it would be on topic would be the FDE mailing list or the flutter-dev mailing list.

**Comment by rundong08** [comment]
The following steps work as a quick and dirty porting:  

1. copy `sqflite/ios` as `sqflite/macos`
2. Modify `sqflite/macos/sqflite.podspec`
    * Change `s.dependency 'Flutter'` to `s.dependency 'FlutterMacOS'`
    * Add `s.platform = :osx, '10.11'`
    * Remove iOS specific parts
3. Change the framework `<Flutter/Flutter.h>` into `<FlutterMacOS/FlutterMacOS.h>`
4. Change the handler of `getPlatformVersion` to call macOS APIs
5. Change `pubspec.yaml`: specify pluginClass for each platform, using the [new format](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms)

Currently, there is no need to write a  Swift wrapper. The existing Objective-C wrapper `SqflitePlugin.m` seems work fine after the above modification.

See https://github.com/rundong08/sqflite/commit/c0a4f4dac81498cc5049ea99704f398c076cc434 for detailed modifications.

**Comment by stuartmorgan** [comment]
@alextekartik Regarding your earlier comment, several Flutter/plugins plugins have macOS support now, using the federated model. Federation is optional though, so it's up to you whether macOS support goes directly into the package, or you switch to a federated structure and have macOS separate.

**Comment by alextekartik** [comment]
Thanks @rundong08 that looks like a really easy support to add.
@stuartmorgan Since I have not tried flutter desktop yet, hard for me to choose between federated, in package, separate. After @rundong08 's comment, I like the idea of adding it right into the package. A few question before I tacke this.
* Are there any example of plugin with macOS support (in the same package)?
* I guess that will only work on the flutter master branch for now, will it break for other platform on stable?
* In a same way, is it easy to add macOS support on the example app (Should I just create a new project with macos support and copy the macos folder in my existing example)?
* Is it possible to share plugin native code between iOS & macOS. It sounds like a simple ifdef could allow maintaining the native part on the 2 platforms.

Thanks @stuartmorgan and sorry for not getting too much attention on desktop yet.

**Comment by stuartmorgan** [comment]
> Since I have not tried flutter desktop yet, hard for me to choose between federated, in package, separate.

Federation is designed to allow different people to maintain different platform implementations separately, in separate repositories. If you plan to maintain the macOS version, there's no need to federate it. (flutter/plugins is unusual in that it federates in the same repository; this is purely to make sure that the Flutter team is testing federation.)

> Are there any example of plugin with macOS support (in the same package)?

If you enable macOS support via `flutter config`, then create a new plugin, it will include macOS.

> I guess that will only work on the flutter master branch for now, will it break for other platform on stable?

As of the last stable release, the new plugin schema in pubspec.yaml works on stable.

> In a same way, is it easy to add macOS support on the example app (Should I just create a new project with macos support and copy the macos folder in my existing example)?

You can `flutter create .` in that folder after enabling macOS, and it will add it. (You can revert any changes to ios/ or android/; you may get some due to changes in those template since you first made the example app.)

> Is it possible to share plugin native code between iOS & macOS. It sounds like a simple ifdef could allow maintaining the native part on the 2 platforms.

The plugin system doesn't have any way to do that, so if you want to share code it would need to be via extracting common code to a Pod.

**Comment by alextekartik** [comment]
I finally took the time to work on this issue. I'm still pretty bad at objectiveC but was able to make it work thanks to @rundong08 first stab on this.

I took the decision to bundle MacOS support in the same package. It does not seem to hurt current stable behavior.

To make sure I did not break anything I published a dev version to pub: 1.2.0-dev.1 so I would appreciate if anyone has a project with sqflite and no unsupported macOS plugins to try it before making it 1.2.0.

My tests were:
- running flutter driver test on the 3 platforms MacOS/iOS/Android
- run the example app on the 3 platforms.
- run another project https://github.com/alextekartik/flutter_app_example/tree/master/notepad that use indexed db on top of sqflite. I was able to run the project on 4 platforms (Web/MacOS/iOS/Android)

For code sharing, I decided to write portable code for both MacOS and iOS with an ugly copy between the 2 (the source being MacOS) and some ifdef.

I have not tried e2e testing yet and still wonder how I could run native tests on a CI (current travis test is only on the dart code so hard to know if the native code breaks).

Thanks @stuartmorgan and @rundong08 for taking the time to help me on this.

**Comment by craigomac** [comment]
It's working well for me on macOS using the `1.2.0-dev.1` release. My use case covers creating two tables, querying and updating them. Thank you for the update!

**Comment by alextekartik** [comment]
Thanks @craigomac for the confirmation. I did more tests on my side as well as minor MacOS specific issues and tests. I published 1.2.0 that now supports iOS/Android & MacOS.

That won't close this bug yet as it was about supporting desktop more generally. I guess Linux and Windows will be next but I will wait for the other official plugin implementation first.

**Comment by MayeulC** [comment]
For reference, that support was added as part of https://github.com/tekartik/sqflite/commit/04623e1f409faec9a1ac0a9610816e749196dca5 (would have been nice to link to it).

It can serve as a reference for implementing it on other OSes.

**Comment by alextekartik** [comment]
I started windows and linux desktop support using ffi (actually using moor_ffi). It will likely be a different project until plugin mechanism is settled for windows and line. I have a sample app here https://github.com/tekartik/sqflite_more/tree/master/sqflite_test_app

Make sure you manage to build the google embedded example first https://github.com/google/flutter-desktop-embedding. It if does not work, this will not work

Hot restart will fail if done while a transaction in in progress.

**Comment by hotlittlewhitedog** [comment]
> Thanks @craigomac for the confirmation. I did more tests on my side as well as minor MacOS specific issues and tests. I published 1.2.0 that now supports iOS/Android & MacOS.
> 
> That won't close this bug yet as it was about supporting desktop more generally. I guess Linux and Windows will be next but I will wait for the other official plugin implementation first.

@alextekartik Hi, do you have some dates about the official plugins implentation? I searched a lot yesterday but it's difficult to find when MacOS will be stable (MacOS Desktop is in Beta state, right?). A lot of packages are now ready for Linux and MacOS, so I really hope that your project will be next :) For info, my project (Bible App) works great with MacOS emulator (Catalyst? via "Flutter run") but I'm unable to start via Xcode (crash at start). Probably not related to Sqflite.

**Comment by alextekartik** [comment]
Currently MacOS sqflite plugin is as stable as the iOS implementation (it is actually the same source code). I was not aware that flutter MacOS desktop was in Beta state but that should not change anything.

Window and Linux support are supported using ffi, some instructions here: https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md

> Hi, do you have some dates about the official plugins implentation?

I was not sure whether this question was regarding all officials flutter plugins but well...I'm not from google and I'm not more up to date than anyone else!

**Comment by hotlittlewhitedog** [comment]
@alextekartik  For info, milestones are here: https://github.com/flutter/flutter/milestones

**Comment by alextekartik** [comment]
I have added some docs on this topic:
* [Notes about Desktop support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/desktop_support.md)

that I copy here for quick reference:

# Desktop support

`sqflite` only includes native Android, iOS and MacOS support. 

Desktop support is provided by [`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi).
Since support is provided both on flutter and on DartVM on MacOS/Linux/Windows, it is not a flutter plugin.

See also some notes about how to keep you sqflite code as is and [supports Windows and Linux](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md)
