### ISSUE TITLE
Add support for SQLCipher

### ISSUE THREAD

**Issue by jorgecoca** [tekartik/sqflite#203]
As a developer, I think it would be a great option to have additional support for encryption via SQLCipher, but before making any changes, I'd like to understand if this is something that the main maintainers would like to see in this project, or would prefer a separate plugin/module, or even a fork. Thoughts?

Thank you so much!

**Comment by jorgecoca** [comment]
Nevermind, it seems a dup of https://github.com/tekartik/sqflite/issues/32

**Comment by alextekartik** [comment]
Thanks for the note. This has been discussed several times indeed (whether it is for bundling a fixed version of sqlite or use sql cipher). It could indeed share a lot of code. However due the way plugin works currently bundling sqlcipher adds about 8mb on Android and I know some project/people won't need/allow that. My plan was to create a shared project between sqflite and let say a new project call sqflite_cipher but since I don't have any project that needs that nor contracts for dedicated time, nothing has been done yet...
