### ISSUE TITLE
Do more conditions help the query proceed faster?

### ISSUE THREAD

**Issue by hyperpanthera** [tekartik/sqflite#211]
For example more 'WHERE' conditions vs. just fetching the entire database?

**Comment by alextekartik** [comment]
Fetching a lot of data will be definitely slower than fetching less as converting data from the native world to the dart world is not free. Regarding sqlite performance itself, that is more a question for sqlite rather than sqflite so I cannot really tell as it depends a lot on your query (i.e. if your WHERE clause is complex it can be slow)

**Comment by hyperpanthera** [comment]
@alextekartik Thanks. Due to things being natively faster, you advise me only to fetch the data I need by using 'WHERE' conditions for example rather than fetching it all, caching it into a map and processing it on the dart side?

**Comment by alextekartik** [comment]
It is always hard to give generic recommendations. It is always easier to have everything in memory in the flutter UI world for synchronous access. Personnally I have an have with about 5K record and where I load everything (i.e. about 5 strings per record) in memory and another that could have 100K records where I load by page (OFFSET, LIMIT)

**Comment by hyperpanthera** [comment]
Thanks a lot.
