### ISSUE TITLE
Copy the db file from the assets, but the existing table in the db file fails to read. 

### ISSUE THREAD

**Issue by gaojuanjuan** [tekartik/sqflite#237]
Copy the db file from the assets, but the existing table in the db file fails to read. When the table is queried, the error message shows that there is no such table. (Sometimes success sometimes fails)

**Comment by alextekartik** [comment]
There was a similar issue where you might get some advices here: https://github.com/tekartik/sqflite/issues/205

Since you don't get much detail, have you looked at the documentation here? : https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md

You might consider posting some code on what you are doing on Stack Overflow to get help from the community. Thanks!
