### ISSUE TITLE
PlatformException when hot restarting a flutter App

### ISSUE THREAD

**Issue by escamoteur** [tekartik/sqflite#257]
Just stumbeled upon this here. When I hot restart my App I get this exception: 
`Cannot perform this operation because there is no current transaction.`

It happens in a call to `SqfliteDatabaseMixin.openDatabase`in database_mixin.dart`

Actually I don't use sqlite directly but through `flutter_map` which uses `flutter_cache_manager`.

You can easily reproduce it by running the example App of https://github.com/johnpryan/flutter_map
and hitting hot restart (not hot reload!)

It makes development currently a bit tedious because I always have to stop and restart the whole App

**Comment by alextekartik** [comment]
Thanks for the report.

Can you confirm that it stops the app? Are you on iOS or Android? There is indeed a hack to support hot reload (I'm assuming you use the latest version of sqflite - if needed try flutter upgrade). It should be only a log from the native side, not a platform exception. On Android, the dart code restarts while the native side is still alive so if a transaction was in progress, sqflite triggers a 'rollback' to cancel the pending transaction otherwise we're stuck. I have not tested much iOS development as I do everything on Linux. 

I just tried the app on the android emulator on linux and several hot restart without issue. 
Can you confirm your platform (and more logs if you have) Thanks!. 

I'm out next week so I will likely not look at it before the week after, sorry...

**Comment by escamoteur** [comment]
Hi @alextekartik, thanks for the quick response.
I'm working on Windows maybe that is a difference? I'm running on Android simulator. Did you enable break on all exceptions?
Just checked if I disable it its fine.

**Comment by alextekartik** [comment]
On linux, even with break on all exceptions and debugging it is fine (in my quick test). I will test on Windows but as I said not before a week so good if you can live with it for now.

Since my hack is only for this 'hot reload' case (believe me, it is worst otherwise), I can likely be smarter and only perform a rollback if there was a 'begin' before on the native side (I was avoiding sql parsing as much a possible). it will be slightly more hacky but I know how important hot restart is.

**Comment by alextekartik** [comment]
I would be interested to know if this is fixed for you if you upgrade sqflite to 1.1.6+4 released today. Thanks!

**Comment by NotThatBowser** [comment]
I had run into the same issue (on Windows) and upgrading to 1.1.6+4 does appear to have resolved it.

**Comment by escamoteur** [comment]
@nothatbrowser great that you confirm it because I only use the package indirectly over another package.

**Comment by escamoteur** [comment]
It seems fixed! Thanks
