### ISSUE TITLE
Handling of SQLiteBlobTooBigException

### ISSUE THREAD

**Issue by bambinoua** [tekartik/sqflite#306]
Hi!
It happens I need to store big images (more than 2Mbytes) in SqLite database. It is saved but when I tried to read it I got and exception **SQLiteBlobTooBigException** (_Row too big to fit into CursorWindow..._) I investigated and found that Android API 28 has the possibility to set the size of this  [CursorWindow(String name, long windowSizeBytes)](https://i.stack.imgur.com/rU4kS.png). Is is possible to implement this in Sqflite package?

P.S. Unfortunately I don't know if this feature is required for iOS.
P.P.S. Is it possible to implement [columnStream](https://almworks.com/sqlite4java/javadoc/com/almworks/sqlite4java/SQLiteStatement.html#columnStream(int)) for reading big BLOBs?

**Comment by alextekartik** [comment]
Thanks for the information. I would really not encourage people using such blob. Since the data is copied from the native to the dart world, this is really inefficient when reading and writing. As it is now we cannot implement a columnStream read. The whole blob content is packaged in an in-memory byte array.

So yes such option could be added but reading such blob will remain slow (and blocking other calls in the mean time).

For my information do you also get an error on iOS for blob bigger than 1Mb?.

You should also consider saving big images as files.

**Comment by bambinoua** [comment]
> For my information do you also get an error on iOS for blob bigger than 1Mb?.

Yes. This is SqLite error not device,

> You should also consider saving big images as files.

It is impossible because security reasons.

P.S. Now I just decrease resolution and quality of stored images. Looks like all is ok with CursorWindow.

**Comment by alextekartik** [comment]
Thanks for the information. Good that you find a workaround. I find the 1Mb blob limit a good limitation (firestore has a similar limit) since otherwise performance would be pretty bad.

>> You should also consider saving big images as files.

> It is impossible because security reasons.

There is no security neither in sqflite. You could encrypt your image.

But well you have your reason. Since you find a workaround, If that's ok for you, I'd like to close this as "Won't be fixed".

**Comment by bambinoua** [comment]
I agree.
