### ISSUE TITLE
getting an exception while retrieving image stored as base64 in the database

### ISSUE THREAD

**Issue by LaxmikanthMadhyastha** [tekartik/sqflite#353]
Im using this package to store messages and these messages have image and I'm storing these image as base64 in the in the database..it inserts the row successfully but when retrieving the same it gives following error

```DatabaseException(Row too big to fit into CursorWindow requiredPos=0, totalRows=3) sql 'SELECT * FROM message_table WHERE message_identifier=?' args [78f32e00deaa5e67a5a603cddddd0b24caregiver]} ```

**Comment by alextekartik** [comment]
This has been reported here: https://github.com/tekartik/sqflite/issues/306

and closed as ... won't be fixed, sorry. 

There seems to be a limit of (around) 1MB when reading on Android and iOS. I could not find a portable way to allow the developer to change this limit.

I find the 1MB blob limit a good limitation (firestore has a similar limit) since otherwise performance would be pretty bad.

Solution: reduce the size of your blob or store your data in a external file and only save a reference to it in SQLite.

I added the same notes here for future reference: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/handling_errors.md#limitations

In your case, I suggest using an external file or reducing the size of your images

**Comment by LaxmikanthMadhyastha** [comment]
okay thanks for the quick response
