### ISSUE TITLE
Maybe not issue but feature request. Why I cannot access `SqfliteDatabaseException`?

### ISSUE THREAD

**Issue by bambinoua** [tekartik/sqflite#383]
I have access to `DatabaseException` but I need access to `SqfliteDatabaseException`. Is it possible to make this class public. Moreover they both are in the same file. I need access to `message` and `result` property to be more flexible for user notifications.

Also is it possible to create method `isNoSuchColumnError`?

**Comment by alextekartik** [comment]
Yeap I understand the need. Unfortunately so far the message and result are not always consistent on each platform so it is hard to make assumption on it (and testing is a pain). I think message could be safely be in the base class `DatabaseException` (but message can differ as well depending on the platform). result however is really internal and for debugging purpose.

Currently message is used to extract basic message (constraint, syntax error), I'm not sure what you would need from the result property (which is dynamic but in fact a map).

When I add a public property it means it is here forever so I want to be safe on that. I think I could add `isNoSuchColumnError` but i need more testing first (on ios/android). I'd rather add specific needs first so do you have some specific expectation (such as `isNoSuchColumnError` like you mentionned) on what you want to report to the user (nosuchcolumn is more a developer error than what a typical user would expect seeting)

**Comment by bambinoua** [comment]
The problem is I have dirty message like `DatabaseException(bla bla bla...)`. I cannot display it to user! It is messy. If I can have `code`, `message`, `result` map etc I can use combination of this info to create my own user friendly message. For example `message` contains `cannot find column "SomeColum"`. I can display it. If need more details (like `sql`) I could use `result` for getting required key.
P.S. Actually I still didn't catch how to use methods like `isNoSuchTableError` etc... How can I get what table name is incorrect?

```
if (isNoSuchTableError()) {
  print(e.toString()); // Here very long and absolutely useless message
}
```

**Comment by alextekartik** [comment]
The message comes from SQLite not sqflite and you are not supposed to display it to the user. In general no error should happen unless you have a developer mistake. isNoSuchTableError is a basic parsing of the message text from SQLite. If you need to find which table is missing you have to parse the text, there is not much else you can do, that is the only information we get from SQLite. even the helper to get the error code is a (bad) parsing of the text that don't work on all platform. I don't even recommend using such helper (isNoSuchTableError) since it might not work consistently on all platform.

* `message` is the only information we get from SQLite
* `code` is computed from message and it is not garantueed to work you have to test on all platforms
* `result` is build from the query you send (so you already know) the query

I could expose `message` and you could do your own parsing but you can already do that using .toString() on the exception. I am not sure I understand the scenario you are trying to solve, no user should get a no such table or no such column, unless you are building a sqlite database manager for developers.

Can you tell me what kind of message you are getting that you want to display to the user?

**Comment by bambinoua** [comment]
For example, I create SQL query for some table and I mistaken in name of column. Now when I do `print('$e')` I see (as user) something like this: 
```
DatabaseException(no such column: ColumnName (code XXX sqlite syntax error)) while compiling SQL query `SELECT ... `
```
I would like to display for example only `No such column: ColumnName` and when I click button `details` I can see SQL query etc.. 

P.S. Please make class `SqLiteDatabaseException` public :) It is easy to do...

**Comment by alextekartik** [comment]
If you really need SqfliteDatabaseException, the easiest for now is to import the file directly:

```dart
import 'package:sqflite/src/exception.dart';
```

I know handling exception is a pain but it is really not consistent accross platform so I don't want to expose something that is not fully working. Here you are trying to present to the end user something that should be handled at the developer level and exposing the internals of sqflite to the end user is not supported for now. If you look at the Android Sqlite API, they don't expose anything neither for this, the error is just a plain text.

**Comment by bambinoua** [comment]
> If you really need SqfliteDatabaseException, the easiest for now is to import the file directly:

I tried this! But I saw warning `Don't import implementation files from another package.` It looks like it is not good idea to import from `source` files.

If no so no. Please skip it. Thanks.
