### ISSUE TITLE
Is it possible to do something like setForcedUpgrade()?

### ISSUE THREAD

**Issue by Xihuny** [tekartik/sqflite#417]
I have used [https://github.com/jgilfelt/android-sqlite-asset-helper](https://github.com/jgilfelt/android-sqlite-asset-helper) package to force upgrade the database when the db version is upgraded. Is it possible to do this in **sqflite**? I don't want to alter the database schema on upgrade. I just want to replace the whole db.

**Comment by alextekartik** [comment]
I'm not sure what this package does. If it is about importing sql script, that is not possible. You can however use batch to run multiple commands.

Since the API of sqflite is largely inspired from the Android sqlite database, the migration mechanims is similar. It is described here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_db.md#migration but you can use the database version (or a custom singleton value) to perform your own check and migration mechanism.

**Comment by Xihuny** [comment]
@alextekartik your answer [here](https://stackoverflow.com/a/61308122/3454744) helped. closing this now.
