### ISSUE TITLE
Find out which commands have failed in a batch when continueOnError=true

### ISSUE THREAD

**Issue by mochar** [tekartik/sqflite#428]
When syncing my local database with the remote one, I expect some items to fail due to for example foreign key constraints. This is fine: I remove the successfully synced items from the queue, and run the sync again on the remaining items in the queue. However I need to know which items have failed and which have succeeded without error. 

I sync in (literal) batches of 50 items, each batch uses a _Batch_. I use `continueOnError=true` because fails are expected, but now I do not know which items have failed.

Any help would be appreciated!

**Comment by mochar** [comment]
From [this issue](https://github.com/tekartik/sqflite/issues/402) I understand that failed calls return a null rather than an id (insert) or effected number of rows (update/delete). So what I can do is set `noResult = false` and check which ones are null to find the failed operations. 

This approach has two small issues. First is performance. As you mention retrieving the result in a batch can be costly, and since I don't even use the result it feels a bit like a waste. Second issue, the sync process does multiple operations per item, the amount which can vary over each item (item 1 might use one insert and three updates, item 2 might use ten inserts and fifteen updates, ...). When I retrieve the results on batch commit, I need to track down which results belong to which item, check which ones have failed, and update the queue table accordingly. It's just a bit messy.

In [this issue](https://github.com/tekartik/sqflite/issues/121) you introduce the `continueOnError` parameter based on someone's issue that is similar to mine. In there you also mention an alternative that might be more useful for me, which is to do the syncing within a transaction and surround each insert/update/delete calls with try/catch to identify the failing commands. However I do not get how this works, isn't a transaction specifically for running a batch of commands that undos everything on a single fail? Example code can help a lot here.

Thanks so much and sorry for the 500-word essay!

**Comment by alextekartik** [comment]
You cannot indeed handle errors correctly when using continueOnError.

Using Batch, you have to know the index of the command to find the result, there is no simpler way that I could think of. And indeed if you have heterogenous commands, it becomes messy. If you have 50 inserts and only inserts, it is simple.

Regarding using a transaction. A transaction is cancelled if an exception is thrown. If you catch it during the transaction only the failing command is cancelled. So basically if you want to cancel a transaction at any time (reverting all commands), simply throw an exception. You can surround each of your command to know what fails depending on how much information you need to report to the user.

Alternatively, you could avoid the foreign constraint (my recommendation) which are hard to deal with in a batch, by simple first getting the list of conflicting keys `SELECT id WHERE my_remote_id IN (?,?,....)" first in your transaction instead of trying to write directly and only write the records that won't fail.

**Comment by mochar** [comment]
Thanks Alex! I'm so sorry I cannot test this now, but the following transaction should work for me then?:

```
await database.transaction((txn) async {
  for item in items_that_need_to_sync:
    try:
      txn.update if item_needs_update or txn.insert if item_is_new
      // remove from sync queue because successfully synced
      txn.delete item from sync_queue
    catch:
      // do nothing to leave item in queue for next sync   
});
```

Can you comment just a little on the performance of this vs batch with `noResults=false`? 

Regarding your last suggestions, I really wouldn't know which items would lead to a constraint. In theory none of them should, but there are edge cases that I need to take into account just to be sure.

**Comment by alextekartik** [comment]
> Can you comment just a little on the performance of this vs batch with noResults=false?

Having to result means less SQL calls and data manipulated by flutter services.

**Comment by mochar** [comment]
Thank you, Alex.
