### ISSUE TITLE
Field name should be always double qouted (?)

### ISSUE THREAD

**Issue by cezaryjk** [tekartik/sqflite#463]
Hi, 
Thanks a lot for great package!
But sometimes when I try to insert new record in database delivered by end-user I get exception. 
It's because of "strange" (but "unfortunately" allowed) character in field name. For example semicolons e.g. "Username**:**"  
Any chance for update? 
BR
Cezary

**Comment by alextekartik** [comment]
Hi, I'm not sure what you mean by field name. Is it a column name? Do you have some sample code to reproduce the issue you are seeing and the kind of update you expect?

**Comment by cezaryjk** [comment]
Sorry. Yes, I mean column name. 
Attached an error and database table structure.
![SQLite_material_semicolonInColumnName](https://user-images.githubusercontent.com/12769666/85181728-eecd1180-b286-11ea-8326-8c55368a70db.png)
![SQFLite_insert_issue_semicolonInColumnName](https://user-images.githubusercontent.com/12769666/85181736-f2609880-b286-11ea-8f91-3dce67875a51.png)

**Comment by alextekartik** [comment]
Arg! Indeed that's pretty bad. That is definitely not something expected in a typical database. I'm not sure we need to always double quote just for this unusual edge case...I will see if something can be done without impacting performance (maybe just double quote if the name contains non alphanumeric characters). In the mean time, you'll have to use rawInsert/Update/Query for this.

**Comment by cezaryjk** [comment]
Yes, naming is lousy ;) Just because tables are imported from excel sheets...
I will sanitize them for now.
Keep my finger crossed for painless solution :) 
Thank you!

**Comment by alextekartik** [comment]
After some testing, it is unfortunately not a safe change. While we could "escape" key name in insert and update map, one will not understand why it is sometimes escaped and sometimes not.

Let me explain. If we always double quote in insert and update, you will wonder why columnName in `query(table, columns: [columnName])` is not escaped. Here it is more complex as columnName could be `COUNT(*)` or `my_column AS my_other_name` that should not be escaped or `name_with_semicolumn:` that should be escaped so it means doing SQL parsing which sqflite does not currently. That could be a breaking change.

Currently [escapeName](https://pub.dev/documentation/sqflite_common/latest/sql/escapeName.html) is very lame, it only escape SQLite keywords. After I improved it to support your case, since it is used in many places, i had several failing test case. So your issue helps pointing that for which I don't have a good solution yet.

So I'm not sure yet of the best choice since nobody complains about that so far.

For example even `COUNT(*)` or `""` is a valid column name so there is no good rule to know if it should be escaped (should double quote be quoted or not?) as a column or not:
```dart
// This works!
await db.execute('CREATE TABLE Test ("COUNT(*)" INTEGER)');
// This works too!
await db.execute('CREATE TABLE Test2 (\'""\' INTEGER)');
```

Currently you can so something like that in your insert/update to always double quote your keys
```dart
await db.insert(
          'Test', map.map((key, value) => MapEntry('"$key"', value)));
```

I'll do more testing but I definitely don't want to introduce any compatibility issue. Also maybe when you import from csv/excel, you could sanitize as you mentioned the column names.

The helpers API are not made for data the developers does not know about. the raw API can allow anything you want and maybe some 3rd party sql builder (there are some on pub) could deal with this in a better way.

**Comment by cezaryjk** [comment]
Hi Alex,
Thank you for your quick response and attempts to solve my problem.
I am also of the opinion that it is better not to spoil something that works properly when we stick to the set requirements. 
Now that I know, I will simply replace or remove illegal characters.

I think you can close this issue.
Best regards
Cezary
