### ISSUE TITLE
cannot create database when copy release app to another path in windows

### ISSUE THREAD

**Issue by amasahara** [tekartik/sqflite#483]
I have a problem when i copy release or debug folder to another path location, database cannot create at new location, i have issue here [https://github.com/flutter/flutter/issues/62020](url) and my repository  [https://github.com/amasahara/Flutter_Todos_Windows](url) 
with debug or release folder it will be fine
![runok](https://user-images.githubusercontent.com/5392719/88248051-06564a80-ccca-11ea-8ad1-1975f1eeaad6.png)

but when i copy to another location it not work
![nôtk](https://user-images.githubusercontent.com/5392719/88248048-048c8700-ccca-11ea-8267-13fb85059ae4.png)

**Comment by alextekartik** [comment]
I don't a windows machine to take a deeper look now but what could be happening is that it could not find the sqlite3.dll. It works from your project because `sqfliteFfiInit` does some initilization and bundle a windows version at a specific location.

sqflite ffi uses https://pub.dev/packages/sqlite3 that has some doc on how to find and load the sqlite dynamic library.

You will likely need to copy the sqlite3.dll (there is version in sqflite_common_ffi package: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi/lib/src/windows) to your application folder and add a specific initialization for a production build: https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3#manually-providing-sqlite3-libraries

Sorry for not having a more easy to use model for now but it is still not clear how dynamic library should be published and bundled so you have to make extra steps for now.

**Comment by amasahara** [comment]
Thanks you for your advice seem rather hard for working on windows
