### ISSUE TITLE
windows release run error

### ISSUE THREAD

**Issue by wechatobok** [tekartik/sqflite#530]
I can't say english well，so i will say chinese
当我使用flutter build windows 命令编译出windows版本后，在原位置双击程序可正常运行，当我把程序拷贝到电脑其它位置时，程序不能访问数据库，即使我把sqlite3.dll拷贝到 .dart_tool\sqflite_common_ffi\src\windows文件夹下也不行，逐步查看源码，我猜测是setup.dart中findPackagePath函数返回值出错，我将返回值直接改为“lib”，然后把sqlite3.dll拷贝到 lib\src\windows文件夹下即可正常运行
void windowsInit() {
  var location = findPackagePath(Directory.current.path);
  //我新加的，I replace value of location there！
  location="lib";
  var path = normalize(join(location, 'src', 'windows', 'sqlite3.dll'));
  open.overrideFor(OperatingSystem.windows, () {
    // devPrint('loading $path');
    try {
      return DynamicLibrary.open(path);
    } catch (e) {
      stderr.writeln('Failed to load sqlite3.dll at $path');
      rethrow;
    }
  });

  // Force an open in the main isolate
  // Loading from an isolate seems to break on windows
  sqlite3.openInMemory().dispose();
}

**Comment by nabil6391** [comment]
the windowsInit() function is actually there as a means to test sqliteffi. If we want to ship sqlite3.dll with our release build then we have to place the sqlite3.dll into the root of our released app folder, meaning alongside our primary *.exe

Then instead of using their windowsInit(), use this:

`
void windowsInit() {
String path;
if (kReleaseMode) {
var location = Directory.current.path;
path = normalize(join(location, 'sqlite3.dll'));
} else {
var location = findPackagePath(Directory.current.path);
path = normalize(join(location, 'src', 'windows', 'sqlite3.dll'));
}

open.overrideFor(OperatingSystem.windows, () {
  print('loading $path');
  try {
    return DynamicLibrary.open(path);
  } catch (e) {
    stderr.writeln('Failed to load sqlite3.dll at $path');
    rethrow;
  }
});

// Force an open in the main isolate
// Loading from an isolate seems to break on windows
sqlite3.sqlite3.openInMemory().dispose();
}
`

**Comment by alextekartik** [comment]
I published a new version that should work if you put the sqlite3.dll next to your executable
