### ISSUE TITLE
Closing database in one isolate will close database in all isolates

### ISSUE THREAD

**Issue by matejdro** [tekartik/sqflite#558]
It appears that this plugin does not handle database closing well when using the database from multiple [isolates](https://api.flutter.dev/flutter/dart-isolate/Isolate-class.html):

1. Create isolate A
2. Create isolate B
3. Open database in isolate A
4. Open database in isolate B
5. Close database in isolate B
6. Attempt to access database in isolate A (where it was not closed)

Step 6 will throw `Unhandled Exception: DatabaseException(database_closed 1)` error.

Only good workaround I found is just keeping the databases open all the time, which, while not a good practice, seems to be working.

**Comment by alextekartik** [comment]
Unfortunately, sqflite is not cross isolate safe. Access should be done in the main isolate only.

- sqflite native access already happens in a background native thread
- Transaction mechanism is not cross-isolate safe

https://github.com/tekartik/sqflite/blob/2474ee295f101808a55a93e6a3e2d42d46cb9366/sqflite/doc/usage_recommendations.md#isolates

**Comment by matejdro** [comment]
Yeah unfortunately confining to main is not possible in our case. We are doing background processing (native side calls flutter code when main UI is not open and thus is has no choice but to create new isolate).

**Comment by alextekartik** [comment]
I understand. That is unfortunately a case where there is no good cross platform solution. On android, one solution is to use `singleInstance = false` when opening the database. You might end up having lock situation to deal with. on iOS, my last experiment with multiple instances/thread lead to non-consistent data in a transaction.

Sharing the same database with a single instance between the isolate means that closing the database closes it for both sides which is what you are seeing. I do recommend keeping the databases open but here anyway sqflite transaction mechanism is not cross isolate safe yet so you might need a kind of mutex too.

I have not done much work in this area since I always manage to work around the need but i understand the need and I see what solutions could be found. That likely won't happen after nnbd migration complete though, sorry.
