### ISSUE TITLE
Question about transactions and async

### ISSUE THREAD

**Issue by marcoberetta96** [tekartik/sqflite#584]
Hi!
I have a doubt about transactions and async methods.
Suppose to have a database with a single table and a class like the following one.

```
class DbHandler {
  static Database _db;

  static readSomething() async {
    return await _db.rawQuery( ... );
  }

  static writeSomething() async {
    await _db.insert( ... );
  }

  static writeOrUpdateSomething() async {
    await _db.transaction((db) async {
      var x = await db.rawQuery( ... );
      if (x.length > 0) {
        await db.update( ... );
      }
      else {
        await db.insert ... );
      }
   }
}
```

Basically there are three methods for:
- read something
- write something
- update a row if existing, or insert it

Question is: how Flutter SQLite handles different operations among different methods?
What happens if the transaction in the third method fails because second method inserts some new rows? Is the transaction re-executed? Or SQLite stops the operation in the second method until the third method has finished?

Thanks!

**Comment by alextekartik** [comment]
Good question on which the doc has no clear response. Some personal responses, maybe a better wording could be found:

* Every read/write/transaction operation is protected by a global mutex on the database. Each action runs one after the other, first
  action called, first ran. While it is a conservative solution, due to some
  native implementation, you can design an app which remains fast.
* `transaction` handle the 'all or nothing' scenario. If one command fails (and throws an error), all other commands called during the transaction are reverted. You can also throw an error to cancel a transaction.
* No other concurrent modification on the database (even from an outside process) can happen during a transaction,  
* When an error is thrown during a transaction, the action is cancelled right away and previous commands in the transaction are reverted,
* The inner part of the transaction is called only once, it is up to the developer to handle a try-again loop - assuming it can succeed at some point.

**Comment by marcoberetta96** [comment]
Hi Alex, many thanks for your very detailed answer! Appreciate!
