### ISSUE TITLE
Could you extend the support for Desktop,Linux and web ?

### ISSUE THREAD

**Issue by raghavan-mookiah** [tekartik/sqflite#609]
Currently the plugin support only ANDROID IOS and MACOS. Do you have a roadmap to support desktop, Linux and web?

**Comment by alextekartik** [comment]
Windows and Linux are supported using sqflite_common_ffi.
See [notepad_sqflite](https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sqflite) for a simple flutter notepad working on iOS/Android/Windows/linux/Mac

There is no persistent sqlite for the web so this is not planned. There is a solution available here though: https://github.com/deakjahn/sqflite_web

**Comment by M123-dev** [comment]
All understandable points.
But it would be good to build a platform check into the plugin natively. That means that everything called from web like `openDatabase()` is simply ignored. This would make it possible to publish lite variants of apps without much effort on the web.

Queries would of course have to be handled differently, but I suspect it should be enough to tell devs that they should build a short check on the web themselves.

```
import 'package:flutter/foundation.dart' show kIsWeb;
if (kIsWeb) {} else {}
```

**Comment by alextekartik** [comment]
The behavior of mocking the database is very opiniated. Especially with nnbd, you cannot easily 'ignored' a call you have to return a value of throw which i guess is the current behavior. My advice is to mock at a higher level if you plan to use a different database on the web.

**Comment by omidraha** [comment]
For desktop I got this error:

```
Unhandled Exception: 
MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
```

Info:

```yaml
  sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.4.1
  sqflite_common_ffi: ^2.0.0
```

```
apt-get install sqlite3 libsqlite3-dev
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!
```

**Comment by alextekartik** [comment]
I have added some docs on these 2 topics:
* [Notes about Desktop support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/desktop_support.md)
* [Notes about Web support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/web_support.md)

that I copy here for quick reference:

# Desktop support

`sqflite` only includes native Android, iOS and MacOS support. 

Desktop support is provided by [`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi).
Since support is provided both on flutter and on DartVM on MacOS/Linux/Windows, it is not a flutter plugin.

See also some notes about how to keep you sqflite code as is and [supports Windows and Linux](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md)

# Web support

sqflite is not supported on the web as there is no decent platform support. 
You can check https://github.com/deakjahn/sqflite_web for an initial web support but it lacks real persistency.
