### ISSUE TITLE
Fetching data datewise from sqflite database

### ISSUE THREAD

**Issue by sanchaykasturey** [tekartik/sqflite#627]
https://stackoverflow.com/questions/67160371/fetching-data-from-sql-databse-in-flutter-datewise

This link contains the question please help me,
Thanks for your replies

**Comment by alextekartik** [comment]
I've seen your questions, unfortunately I don't have a good answer. I'm puzzled by date time SQLite implementation (it seems to store value as local data, where i'm typlically more interested in UTC) so I typically use `INTEGER` (and store ms since epoch) or `TEXT` (store toIso8601) to store date and to perform comparison....which might not help you!
