### ISSUE TITLE
will you support Stetho for easily access sqlite db?

### ISSUE THREAD

**Issue by zinwalin** [tekartik/sqflite#65]
I tried to integrate Stetho and sqflite, so I can debug and access sqlite db from Chrome Dev Tools, but it seems sqflite and Stetho doesn't work together at the moment.

**Comment by alextekartik** [comment]
I'm not aware of Stetho nor whether Stetho integrates properly with Flutter. However sqflite uses regular Android sqlite database so if you manage to make Stetho work with Flutter, it should work. Have you tried without Sqflite?

**Comment by alextekartik** [comment]
Actually reading the stetho's doc is seems that it might be a database location issue (just speculating here). You could either try this: https://github.com/facebook/stetho/issues/445 depending on your location strategy or update to the latest sqflite version (0.11.0) and use getDatabasesPath to specify your database location (instead of path_provider)
https://github.com/tekartik/sqflite/blob/237d3af1afe5bacf1c1b66d4f5102aa79c5ee63c/example/lib/open_test_page.dart#L88-L99

**Comment by zinwalin** [comment]
I was able to access database via Chrome Dev Tools. Point is that when creating database I used Directory path = await getApplicationDocumentsDirectory();. But it returns appRoot/app_flutter directory. Stetho expects databases in appRoot/databases directory. So the trick is to create database file in databases directory:

Future<String> _getPath() async {
    Directory path = await getApplicationDocumentsDirectory();
    if (Platform.isAndroid) {
      return join(path.parent.path, "databases/db.sqlite");
    } else {
      return join(path.path, "db.sqlite");
    }
  }
...
_db = await openDatabase(
      dbPath,
      version: 1,
      onCreate: _create,
    );
—

**Comment by zinwalin** [comment]
@alextekartik Thanks heaps.
