### ISSUE TITLE
Support for sqlite3_limit / SQLITE_MAX_VARIABLE_NUMBER value

### ISSUE THREAD

**Issue by monsieurtanuki** [tekartik/sqflite#663]
In my project I try to optimize my database insert statements, performance-wise.
For instance, I generate statements like `insert into table a(b,c,d) values(?,?,?),(?,?,?)....,(?,?,?)` according to the (variable) number of rows I want to insert.
When the number of `?` parameters exceeds `SQLITE_MAX_VARIABLE_NUMBER`, I have to generate other similar `insert` statements. So far so good.
The only problem I have is that I don't know the actual value of `SQLITE_MAX_VARIABLE_NUMBER` on the smartphone.
I read that the default value is `999` (which seems fair as I crashed my app with `1000` but was successful with `999`).

Is it always going to be `999` in sqflite?
Is there a way to read this value, like with `sqlite3_limit`?

**Comment by alextekartik** [comment]
Unfortunately I am not aware of any cross platform way to get this value. On Android for example the java layer don't expose any internal SQLite API. I cannot ensure that the value will always be 999 (i don't know even know the value) since it can depend on  SQLite bundled and could even depend on the OS version. Although nothing will beat building a single insert statement, you might want to combine single statement with, let say, 10 inserts and batch to get the best insert performance.

**Comment by monsieurtanuki** [comment]
Thank you @alextekartik!
At least I can start with a max number of `999`, detect the possible "too many parameters" exception, and decrease my max number if needed. And store the value in `SharedPreferences`, for the next insert statements.
Feel free to close the issue.

**Comment by alextekartik** [comment]
Smart indeed. thanks.
