### ISSUE TITLE
Is there a roadmap with top priorities?

### ISSUE THREAD

**Issue by omidraha** [tekartik/sqflite#668]
Is there a roadmap with top priorities? 

There are a number of users priorities here:

- **Support web**
 + #212  
 + #385
 + #570
 + #609
 + #37 
 + #562

- **Support Desktop (Windows, Linux, Mac)**
 
 + #470
 + #356
 + #210
 + #502
 + #547
 + #468
 + #365
 + #194

- **Support encryption**
 
 + #32 
 + #218
 + #432
 + #456
 + #500
 + #648

**Comment by alextekartik** [comment]
Thanks for the condensed report of issues/questions that are regularly asked/reported.

There is no roadmap, nor planned evolution at this point. sqflite uses whatever the platform provides in terms of SQLite support and provides a basic common API which is largely based on Android API which has been around for several years without evolution neither. Other support could require bundling a different version of sqlite hence bigger size and choices between multiple options where sqflite cannot make a choice that will satisfy all users (and I can understand the frustration). That is said, nothing prevent evolution (for example sqflite is not cross isolate safe at this point and I plan to fix that - no roadmap nor easy solution currently) and feature requests. And if some request cannot be satisfied (I am a freelance developer maintaining this in my available free time), there is always the possibility to fork and make it better!

I have added some docs on these 3 topics:
* [Notes about Desktop support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/desktop_support.md)
* [Notes about Encryption support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/encryption_support.md)
* [Notes about Web support](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/web_support.md)

that I copy here for quick reference:

# Desktop support

`sqflite` only includes native Android, iOS and MacOS support. 

Desktop support is provided by [`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi).
Since support is provided both on flutter and on DartVM on MacOS/Linux/Windows, it is not a flutter plugin.

See also some notes about how to keep you sqflite code as is and [supports Windows and Linux](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md)

# Encryption support

Encryption is supported on Android, iOS and MacOS support using [`sqflite_sqlcipher`](https://pub.dev/packages/sqflite_sqlcipher)
by David Martos which has some shared code through `sqflite_common` package.

On desktop, encryption is provided by [`sqflite_common_ffi`](https://pub.dev/packages/sqflite_common_ffi).
Since support is provided both on flutter and on DartVM on MacOS/Linux/Windows, it is not a flutter plugin.
See [here](https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/encryption_support.md) for more information
of how encryption is supported on Desktop.

# Web support

sqflite is not supported on the web as there is no decent platform support. 
You can check https://github.com/deakjahn/sqflite_web for an initial web support but it lacks real persistency.
