### ISSUE TITLE
Problem with query in hebrew

### ISSUE THREAD

**Issue by yoavkedem1** [tekartik/sqflite#678]
when I try to query the SQL DB and the data is in Hebrew I don't get any result even though when I write the code in a different SQL environment the code works.
here is an example of the code:
![Screenshot 2021-07-29 112251](https://user-images.githubusercontent.com/34098545/127457985-217d56ee-7956-4e02-9677-018fd04f7333.png)

**Comment by davidmartos96** [comment]
The problem is the use of REGEXP, that is a special case in Sqlite. It's not implemented by default. You need to plug it yourself with the platform you are using. As far as I know it is not possible to do it with the Sqlite version that comes bundled with the mobile devices (which is what sqflite uses). However, if you really need to use Regexp, you can use the moor package instead, which uses Dart FFI + Sqlite native library. It includes an implementation of Regexp that you can use in your queries. 
https://moor.simonbinder.eu/docs/other-engines/vm/#moor-only-functions

**Comment by yoavkedem1** [comment]
As far as I can see the problem is with Hebrew because the problem happens even when I use LIKE operator.
for example
![image](https://user-images.githubusercontent.com/34098545/127818079-562c2e77-d521-46b9-8871-2bc8592883b0.png)

**Comment by yoavkedem1** [comment]
As far as I can see the problem is with Hebrew because i try to use the LIKE operator and get result only if the string starts with the sub string, and i get all the result where the string contains the sub string for example:
![image](https://user-images.githubusercontent.com/34098545/127818630-031b2685-61c7-4b8e-ae2a-5074a7123b45.png)
