### ISSUE TITLE
bool auto conversion

### ISSUE THREAD

**Issue by newlix** [tekartik/sqflite#68]
I am trying to use [json_serializable](https://pub.dartlang.org/packages/json_serializable) to avoid writing toMap and fromMap by hand because it is error-prone. But sqflite expects bool to be encoded as Int in a Map, is it possible sqflite  do the conversion automatically?

**Comment by alextekartik** [comment]
That would be possible when writing
* null => null
* true => 1
* false => 0

However when reading we have to information that is is a boolean so you would retrieve null, 0 or 1. So I don't know if json_serializable can handle that, otherwise the safer is to use an int instead in your class definition and create a setter/getter as a boolean.

**Comment by newlix** [comment]
sorry I am new to Dart. Can I create a Int field with Bool getter and setter with the same field name?

**Comment by alextekartik** [comment]
Nope you cannot it has to have a different name. I don't know json_serializable enough to know what it can do neither

**Comment by newlix** [comment]
Thank for your help. I think the best way is to avoid bool to keep everything simple.

**Comment by newlix** [comment]
hi, can you explain more clearly?

The problem is sqlite doesn't have bool type support. So we have to translate it by hand. 
I didn't find any way to make json_serializable encode bool to int.
