### ISSUE TITLE
Bundle pre-existing db

### ISSUE THREAD

**Issue by stanonyime** [tekartik/sqflite#7]
Are there support for bundling a pre-loaded db file?

**Comment by alextekartik** [comment]
If the pre-loaded is an sqlite database and assuming the sqlite format is the same for all android/iOS version you install your app on it (SQLite db files should be OS independant), you could check if the database file exists on the file system and if not copy a file from your assets to the database path and then open it.
Alternatively you could execute a list of sql statement from a text file (be careful on text encoding here though). Otherwise the safest is to use the onCreate callback and execute statements

**Comment by stanonyime** [comment]
Ok

**Comment by alextekartik** [comment]
FYI the example now includes opening an asset database (copying it to the file system first). Check documentation here:
https://github.com/tekartik/sqflite/blob/master/doc/opening_asset_db.md
