### ISSUE TITLE
SQFLite Plugin Returns null value for boolean-as-text from Database despite being set before

### ISSUE THREAD

**Issue by KevinCCucumber** [tekartik/sqflite#713]
I am writing these Values into my Database:

    {saveid: gWpcHhfpuN4MSTdhF, isObtained: true, isFavourite: false, timestamp: 202110201532, category: VILLAGER, localislandid: 0, localvillagerid: 0}
    {saveid: ebHEDLT4WnnnPtDzK, isObtained: false, isFavourite: true, timestamp: 202110201532, category: VILLAGER, localislandid: 0, localvillagerid: 0}
    {saveid: TksYZm8hEYAeDWD2X, isObtained: true, isFavourite: true, timestamp: 202110201532, category: VILLAGER, localislandid: 0, localvillagerid: 0}

and these are the values when loaded:

    {saveid: gWpcHhfpuN4MSTdhF, isObtained: true, isFavourite: null, timestamp: 202110200547, localislandid: 0, localvillagerid: 0, category: VILLAGER}
    {saveid: ebHEDLT4WnnnPtDzK, isObtained: null, isFavourite: true, timestamp: 202110200549, localislandid: 0, localvillagerid: 0, category: VILLAGER}
    {saveid: TksYZm8hEYAeDWD2X, isObtained: true, isFavourite: null, timestamp: 202110200550, localislandid: 0, localvillagerid: 0, category: VILLAGER}

These are my insertion Methods

    Future<void> insertItem(String tableName, Map<String, dynamic> itemToAdd) async {
        Database db = await this.db;
    
        var itemExists = await this.itemExists(tableName, itemToAdd[colSaveID]);
        itemExists ? await updateItem(tableName, itemToAdd) : await db.insert(tableName, itemToAdd);
        if (dbLogging) {
          if (itemExists) {
            log("ITEM EXISTS ALREADY IN TABLE $tableName, WILL UPDATE INSTEAD; ITEM-ID: ${itemToAdd[colSaveID]}", name: "DB-WARN");
          } else {
            log("INSERTED INTO TABLE $tableName; ITEM: $itemToAdd", name: "DB-INFO");
          }
        }
      }

and:

    Future<int> updateItem(String tableName, Map<String, dynamic> itemToUpdate) async {
        Database db = await this.db;
    
        var result = await db.update(tableName, itemToUpdate, where: "$colSaveID = ?", whereArgs: [itemToUpdate["id"]]);
        if (dbLogging) {
          log("UPDATED 1 ITEM IN TABLE $tableName; NEW VALUES: $itemToUpdate", name: "DB-INFO");
        }
    
        return result;
      }

This is my getting Method:

    Future<List<Map<String, dynamic>>> getAllItemsFromCategory(String tableName, String category) async {
        Database db = await this.db;
    
        var result = await db
            .rawQuery("SELECT * FROM $tableName WHERE $colCategory = '$category'");
    
        if (dbLogging) {
          log("THE TABLE $tableName HAS ${result.length} ELEMENTS IN THE CATEGORY $category: $result", name: "DB-INFO");
        }
    
        return result;
      }

The data is directly taken from the read/write methods but without the cluttery text.
I am quite clueless and I don't know wich more Information I can provide on this topic. 
I expect the read data to be the same as the ones I inserted.

**Comment by alextekartik** [comment]
> I am quite clueless and I don't know wich more Information I can provide on this topic.

I cannot really tell whether `isObtained` and  `isFavourite` are `bool` or `String` (print will display them the same way).
What would help would be to print the type or print the jsonEncode or your data.

> I am quite clueless and I don't know wich more Information I can provide on this topic.

What would help:
- The type of isObtained and isFavourite in your map
- how you declared them in your `CREATE TABLE` statement

> I expect the read data to be the same as the ones I inserted.

My guess is that isObtained and isFavourite are boolean. As stated in https://github.com/tekartik/sqflite/blob/master/sqflite/doc/supported_types.md#supported-sqlite-types, `bool` is not a supported type in SQLite, there's not much we can do here. a boolean `true` will be converted to the `"true"` text and read as text. My suggestion is to use 0 and 1 for false/true value.

**Comment by alextekartik** [comment]
> And the map I get from the database has all the elements looking like the print:

Since this is a list, a print of the map - print(jsonEncode(map)) - before would help (and [null, 'true'] and ['true', null] on 2nd and 3rd position matches what you read if they correspond to isObtained and isFavourite)

> var result = await db.update(tableName, itemToUpdate, where: "$colSaveID = ?", whereArgs: [itemToUpdate["id"]]);
> log("UPDATED 1 ITEM IN TABLE $tableName; NEW VALUES: $itemToUpdate", name: "DB-INFO");

result contains the number of row updated, you should print
```dart
log("UPDATED $result ITEM IN TABLE $tableName; NEW VALUES: $itemToUpdate", name: "DB-INFO");
```
If the result is 0 - if itemToUpdate['id'] is null) - nothing has been updated

> whereArgs: [itemToUpdate["id"]]

As far as I can tell, you have no "id" field (and in this case update would fail since there is no such column). Maybe it should be
```dart
whereArgs: [itemToUpdate[colSaveID]]
```

> rawQuery("SELECT * FROM $tableName WHERE $colCategory = '$category'");

Please use category as an arg, something like
```dart
rawQuery("SELECT * FROM $tableName WHERE $colCategory = ?', [category]);
```

>  var itemExists = await this.itemExists(tableName, itemToAdd[colSaveID]);
>  itemExists ? await updateItem(tableName, itemToAdd) : await db.insert(tableName, itemToAdd);

You should do this in a transaction, there is a race condition where data could change between itemExists and update/insert)

**Comment by alextekartik** [comment]
> I am quite unsure about what the syntax does here. Is the questionmark replaced by category?

Hard to give a full course of SQLite...sqflite is just a wrapper around SQLite. SQLite doc itself is a whole website. You can read about parameter binging here: https://www.sqlite.org/c3ref/bind_blob.html

But yes, in short, parameters replace `?` in the same order they are specified.

sqflite quick doc on it: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#parameters

> Could you give an example on how I can use transactions? 

There is a super simple example here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#transaction
The usage is similar, rather than using directly the database object, you use a transaction object.

> It was quite unclear just from the documentation.

Yes sorry about that. PR are welcome though ;) There are tons of SQLite tutorial and example around the world. sqflite assumes a knowledge about SQLite in general. In general I tend to add example as people ask for it. There is another example of a insert vs update in a transaction with 2 solutions (one with a constraint and one with: if the update count is 0, then insert): https://github.com/tekartik/sqflite/blob/81c0c30aa59d7d3f229bf6ce0494458f96f893c2/sqflite/doc/handling_errors.md#strategy
