### ISSUE TITLE
Migrate to using Android Background Platform Channels

### ISSUE THREAD

**Issue by gaaclarke** [tekartik/sqflite#719]
As of https://github.com/flutter/engine/pull/29346 platform channels support the ability to execute on background threads instead of the platform thread.  This means all the work in sqflite managing its own thread can be removed once that hits stable.

In the meantime I've migrated a few plugins and used reflection to take advantage of the new API if it is available.

Here is an example where I migrated path_provider which also was managing its own thread: https://github.com/flutter/plugins/pull/4443

This should make sqflite perform much better on Android by removing the time on the platform thread, which is often contested, and by making each call 1 thread hop instead of 2.

**Comment by alextekartik** [comment]
>  The API is documented and setup to not guarantee that you actually get your own thread. I plan on moving the implementation to a thread pool

One think I think about is that SQLite locking mechanism is thread based. For example all statements in a transaction must be executed in the same thread. Since this could be done in multiple calls there need to be a garantee that the same thread is used in this case so I'm not sure that having a pull of thread (or simply having different threads between 2 calls) will work here.

**Comment by gaaclarke** [comment]
It will work as long as the calls are serialized.  Sqlite only has a problem if you have concurrent calls into it... well actually it depends on how you compile sqlite but if the calls are serialized it doesn't matter.  The only thing that can get tripped up is `thread_local` storage.
