### ISSUE TITLE
Change argument types from dynamic to Object

### ISSUE THREAD

**Issue by evant** [tekartik/sqflite#73]
If you disable implicit dynamic as such:
```yaml
analyzer:
  strong-mode:
    implicit-dynamic: false
```
Then you get errors on params like `whereArgs` because it uses a type of `List<dyanmic>`.

ex:
```dart
db.query("Table", where: "id = ?", whereArgs: [id])
```
fails with
```
error: Missing type argument for list literal. (strong_mode_implicit_dynamic_list_literal at ...
```
While you can work around it be doing
```dart
db.query("Table", where: "id = ?", whereArgs: <dynamic>[id])
```
as far as I an tell, there's nothing this lib is doing requiring them to be `dynamic`, `Object` works fine.
So if you changed the signature to ex:
```dart
Future<List<Map<String, dynamic>>> query(String table,
      {..., List<Object> whereArgs, ...});
```
then the original verison would work. Let me know if I'm missing anything.

**Comment by alextekartik** [comment]
Thanks for the note. Object vs dynamic always puzzled me. If I follow you, it seems that we should also have `Map<String, Object>` instead of `Map<String, dynamic>` since this fails:

```dart
Map<String, dynamic> toMap() {
  return {'field': true};
}
```

while this compile fine:

```dart
Map<String, Object> toMap() {
  return {'field': true};
}
```

But it seems many APIs (firebase) are using `Map<String, dynamic>` and not `Map<String, Object>`. This [old blog note](https://work.j832.com/2013/09/dart-dynamic-vs-object-in-arguments.html) makes it clear that it should be dynamic and not Object as we don't accept any object (only num, blob and String) in the whereArgs (and we have no union yet) but it refers to a note in the dart style guide that no longer exists.

I've tried once `implicit-dynamic: false` and indeed it is a pain. Maybe should we ask the sdk team why a warning arise here in the first place and what is the recommendation for a list that accept object of different types.

**Comment by rahulmranjith** [comment]
```
class Credentials {
  int id;
  String un;
  String pw;


Credentials(
      {this.id,
      this.un,
      this.pw})

Map toMap() {
    Map map = {
      "un": un,
      "pw": pw}

if (id != null) {
      map["id"] = id;
    }
    return map;
}


//mycard is the object withe values to be saved 

 mycard.id = await db.insert("Credentials", mycard.toMap());


```
I am getting  //type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'

I updated flutter recently. What changes do I need to make .I saw some of your comments in the stackoverflow regarding 
```
analyzer:
  strong-mode:
    implicit-casts: false
```
and in this post about 
```

analyzer:
  strong-mode:
    implicit-dynamic: false
```
Which analysis_options.yaml do I need to change it ? I see multiple analysis_options.yaml when i search my system.

**Comment by alextekartik** [comment]
@rahulmranjith Please create a new issue as this has nothing to with this current issue.

The analysis_options.yaml must be at the root of your package (see https://www.dartlang.org/guides/language/analysis-options) so that you get proper reporting on your code. This package itself has one.

This is a correction to your code:
```dart
class Credentials {
  int id;
  String un;
  String pw;

  Credentials({this.id, this.un, this.pw});

  Map<String, dynamic> toMap() {
    var map = <String, dynamic>{"un": un, "pw": pw};

    if (id != null) {
      map["id"] = id;
    }
    return map;
  }
}
```

**Comment by shareme** [comment]
Thanks for this.. still a lot of drt 1.x code examples around in dart 2.x stuff so this helped me convert over to dart 2 thanks for your helpful post
