### ISSUE TITLE
Give access to result of DatabaseException or export SqfliteDatabaseException

### ISSUE THREAD

**Issue by bambinoua** [tekartik/sqflite#742]
I need to customize exception message and log its details. Now the message is looks like 
```
DatabaseException(... some text)
```
I need to show something more user friendly and log details of error. It would be good to make `result` as part of `DatabaseException` to get access or if it possible export `SqfliteDatabaseException`.

**Comment by alextekartik** [comment]
The errors are not consistent accross all platforms (ios, android, ffi) so it is hard to rely on its content where sometimes only some text is available (sqflite already parses it to extract some error code but it is not always consistent neither).

I'm not sure how to export `result` from SqliteDatabaseException yet since it is completely inconsistent, may be just a `Object? getResult()` or `Object? get result` could help with some doc stating that its content is undocumented and platform dependent (and could change in the future as it is used internally).

**Comment by bambinoua** [comment]
I don't understand why the `export` of `SqfliteDatabaseException` is a problem? If you don't want this why couldn't you move `result` and `resultMap` to `DatabaseException` interface?

**Comment by alextekartik** [comment]
> If you don't want this why couldn't you move result and resultMap to DatabaseException interface?

Well my proposal was:

adding `Object? get result` to DatabaseException with some doc stating that its content is undocumented and platform dependent (and could change in the future as it is used internally).

Is this solution ok for you?

**Comment by bambinoua** [comment]
Oh. It looks like I was unattentive while reading your previous message.
Yes, I think this can help. Thanks.

**Comment by alextekartik** [comment]
result is exported in `sqflite_common` 2.2.0 I just published. A simple pub upgrade should get you the latest version.
