### ISSUE TITLE
WHERE timestamp BETWEEN $fstDateTimestamp AND $lstDateTimpestamp return empty.

### ISSUE THREAD

**Issue by naing-pyae-hlyan** [tekartik/sqflite#767]
Hello.
This is my table..
'CREATE TABLE $tableName('
      '$uniqueIdConst INTEGER PRIMARY KEY AUTOINCREMENT,'
      'timestamp INT,'
      'price INT,'
      'note TEXT,'
      'name TEXT,'
      'qty INT,'
      ')',
      
      
 And I'm trying to get data  between two dates.

  "SELECT * FROM $tableName WHERE timestamp BETWEEN $fstDateTimestamp AND $lstDateTimestamp"    

And trying different way
"SELECT * FROM $tableName WHERE timestamp >= $fstDateTimestamp AND timestamp <= $lstDateTimestamp"

all result is empty.
Please can you help me for this?
Thanks.

**Comment by Muhammadbarznji** [comment]
which data type do you used to store $fstDateTimestamp and $lstDateTimestamp?

**Comment by tuxskar** [comment]
I'm not sure if it is because of your example but you are using the same name for the variables on the between, however with the second statement where using >= and <= it should at least give you some record if there is a record with the exact timestamp as the values used.

For me helps to pull the database from the device and try on a desktop sqlite viewer such sqlitebrowser.

You can search on the current database state the same query with specific values (integers for fstDateTimestamp) and see if you get or not results so you can discard an issue on the library and look more on the query
