### ISSUE TITLE
Sqflite makes flutter integration tests to await forever

### ISSUE THREAD

**Issue by searene** [tekartik/sqflite#841]
Hi, I'm writing a flutter integration test that includes `sqflite`, I've been trying for days, but couldn't make it work. Here is the code:

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:our_habits/my_app.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';


void main() {

  /// Initialize sqflite for test.
  void sqfliteTestInit() {
    // Initialize ffi implementation
    sqfliteFfiInit();
    // Set global factory
    databaseFactory = databaseFactoryFfi;
  }

  testWidgets("Test sqflite database", (WidgetTester tester) async {
    print("start");
    sqfliteTestInit();
    await tester.pumpWidget(const MyApp());

    print("Opening database");
    await openDatabase(
        inMemoryDatabasePath,
        version: 1,
        onCreate: (Database db, int version) async {
        }
    );

    print("end");
  });
}
```

I ran the test with the following command:

```sh
flutter test ./simple_test.dart
```

The test never ends, this is the output:

```
00:03 +0: Test sqflite database                                                                              
start
Opening database
```

As you can see, the last line `print("end")` is never executed. I debugged it for a while, and found that the test stuck on the following line in the `sqflite` source code:

![image](https://user-images.githubusercontent.com/3351317/182009467-670724a4-7a83-4496-8245-b5bcdf8a7ec5.png)

That's weird because I defined the `onCreate` function as an empty one. Then I tried to remove the `onCreate` function in my code, like this:

```dart
await openDatabase(
        inMemoryDatabasePath,
        version: 1,

        // Comment the onCreate function
        // onCreate: (Database db, int version) async {
        // }
    );
```

Then the last line was executed, which means end was output to the console. But the test was still never finished. Then I removed the following line, and finally, the test finished successfully.

```dart
await openDatabase(
    inMemoryDatabasePath,
    version: 1,
    onCreate: (Database db, int version) async {
    }
);
```

It seems that `sqflite` has done something to make the tests wait forever. I've been searching online for a long time but still couldn't find an answer. What's the problem here? How can I make it work?

#### Environment

- Device: iPhone 13 simulator
- OS: macOS

Please tell me if you need anything more.

**Comment by alextekartik** [comment]
Thanks for the detailed report. Since I cannot explain why it hangs, I might say invalid statements.

There are 3 types of testing: unit test, widget test, integration test

I think that what you are doing is not [integration test](https://docs.flutter.dev/cookbook/testing/integration/introduction) as defined in flutter. Integration tests run on the device. Here you are running [widget test](https://docs.flutter.dev/testing#widget-tests). Like unit test, it runs on the host platform (MacOS in your case).

In my experience, in widget test, there are several restrictions like http or isolate. sqflite_common_ffi works fine in regular unit test (https://github.com/tekartik/sqflite/blob/master/sqflite/doc/testing.md). In widget test, it seems that it hangs and one solution is to use the sqfliteFactoryFfiNoIslate instead of sqfliteFactoryFfi.

Can you try replacing:
```dart
// Set global factory
databaseFactory = databaseFactoryFfi;
```
with
```dart
// Set global factory
databaseFactory = databaseFactoryFfiNoIsolate;
```

The doc on unit testing with sqflite is not really up to date. I  will update it.

**Comment by searene** [comment]
Hi @alextekartik 

It really worked! I cannot believe I've been searching for an answer for days. Thanks so much!
