### ISSUE TITLE
rawQuery support null as value

### ISSUE THREAD

**Issue by jksevend** [tekartik/sqflite#848]
Hello
#173 brought me here.
I have a simple one to many relationship. When trying to update the foreign key to null - for example if the foreign key entity is deleted
I get an exception. However I found a workaround by using not so pretty conditional logic:

```
Future<void> updateStackForIds(String? id, List<String> selectedIndexCardIds) async {
    for (var element in selectedIndexCardIds) {
      await _database.rawQuery('''
    update ${Constants.tabIndexCard}
    set stack_id=${id == null ? 'NULL' : '?'}
    where id=?
    ''', id == null ? [element] : [id, element]);
    }
  }
```

But I believe this can be messy the more fields come into place. Can this be done a bit easier and I am missing it?
Any help appreciated!

**Comment by alextekartik** [comment]
(As a side note you should use rawUpdate instead of rawQuery).

Some implementation (ffi) seems to support NULL. sqflite has some little helpers that handle this. Instead of using `db.rawUpdate`, use `db.update` as it will do exactly what you are doing here.

For example:
```dart
await db.update('Test', {'name': null, 'other': 'value2'},
    where: 'id = ?', whereArgs: [2]);
```

will generate:

```
UPDATE Test SET name = NULL, other = ? WHERE id = ? [value2, 2]
```

Of course it is limited and that might not work for complex queries but in your case the following could replace you code in all cases:

```dart
 await _database.update(Constants.tabIndexCard, {'stack_id': id},
        where: 'id = ?', whereArgs: [element]);
```

If that is not enough, you might have to create your own SQL helpers to handle such scenario unfortunately

**Comment by jksevend** [comment]
Thank you very much! Will try it out :)
