### ISSUE TITLE
join argument for query function

### ISSUE THREAD

**Issue by odrevet** [tekartik/sqflite#852]
It is currently impossible to use the query function when the request has JOIN, as the query function do not have a join: argument. 
is it possible to add such option for this function ? thanks

**Comment by alextekartik** [comment]
Do you think of any convenient API for it? There are tons of way to perform a join in SQLite. Personnally I use VIEWS (at some I do a join, not in the query itself but in the view) so that I can use the simple query API instead of the more complete rawQuery.

The SQL support is very limited as it is hard to create an API around such a language as it is quickly opinionated. Maybe some third party has a better support but I cannot think of a simple API on how to specify 1 or more tables and which field should match between the various tables in the query statement.

**Comment by odrevet** [comment]
I was thinking a joins argument as a List of String containing the SQL fragments, kind of the [old ruby on rails find function](https://apidock.com/rails/v3.0.0/ActiveRecord/FinderMethods/find): 

```
db.query(tableTodo,
        columns: [columnId, columnDone, columnTitle],
        joins: ["JOIN tableX ON tableTodo.id = tableX.idtodo", "JOIN tableY ON tableX.id = tableY.idx"]
        where: '$columnId = ?',
        whereArgs: [id])
```

**Comment by alextekartik** [comment]
Not sure an API is needed for that as you can simply put your JOIN logic in the table name:
```dart
db.query(
        'tableTodo JOIN tableX ON tableTodo.id = tableX.idtodo JOIN tableY ON tableX.id = tableY.idx',
        columns: [columnId, columnDone, columnTitle],
        where: '$columnId = ?',
        whereArgs: [id]);
```

**Comment by odrevet** [comment]
This works, thanks
