### ISSUE TITLE
Is it possible to insert data into multiple tables simultaneously

### ISSUE THREAD

**Issue by msarkrish** [tekartik/sqflite#875]
Hi @alextekartik Thanks for this plugin and your hardwork.
I have one scenario, in which I have to insert data into multiple tables simultaneously both in Android and iOS. For example inserting data into Asset and Location table simultaneously in Android and iOS. 
Is this possible with sqflite or not?
If possible then can you provide example to implement this?

**Comment by alextekartik** [comment]
There is nothing specific for that in sqlite. Typically a transaction does exactly that since it either fails all or succeeds all.  Below is a simple example where one record is inserted in each table in a transaction. There is always of course an order in your statement so it is not strictly said _simultaneous_ however it cannot fail for only one record, either both will be inserted (typical behavior), either both won't (typically io/lock error that hopefully will never happen)

```dart
await db
    .execute('CREATE TABLE Author (id INTEGER PRIMARY KEY, name TEXT)');
await db.execute(
    'CREATE TABLE Book (id INTEGER PRIMARY KEY, authorId INTEGER, title TEXT)');

// Insert author and book in a single transaction
await db.transaction((txn) async {
  var authorId = await txn.insert('Author', {'name': 'John Doe'});
  await txn
      .insert('Book', {'title': 'On the mountain', 'authorId': authorId});
});
```

You can get more (poor though) info on transaction usage in sqflite [here](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/sql.md#transaction). If you need better SQLite statement help and information on SQLite transactions, you might also try stack overflow to get a broader SQLite audience.
