### ISSUE TITLE
onCreate run on app upgrade

### ISSUE THREAD

**Issue by daniel-hopkins** [tekartik/sqflite#884]
my pubspec.yaml was setup with `sqflite:null`, and the last time I updated the package it was at 2.0.0+4. This morning after running `pub get` it was automatically updated to 2.1.0+1 (as expected). However, when I ran the app, the onCreate method was run, and it deleted my databases, and reset everything to scratch.

I tested it several times as I wasn't sure what the issue was, but it happened every time.
I checked the change logs, but didn't see anything obvious that would make this happen.
I changed pubspec to `sqflite: ^2.0.0+4`, and I did a fresh install from the play store, and then ran the upgrade from VSCode again, and the database was maintained with no onCreate method getting run.
Running on Android, did not test for iOS or Web.

Thanks

**Comment by alextekartik** [comment]
Sorry for getting back late on this. That is a pretty well tested scenario (although always painful to reproduce) so thanks for reporting it (and indeed I wonder why it worked before and not now). What you can try:
- Upgrade to the latest version (2.2.0+2)
- Share some code where you open the dtabase if you can (I know that sometimes it is not always easy since it could involve a lot of code) to see if I can spot some mistakes.

**Comment by alextekartik** [comment]
(as a side note `sqflite: ^2.0.0+4` should still fetch the latest version when running `flutter pub upgrade`). What might have happen is that some shared depency (sqflite_common) was not properly upgraded in you first `pub get` (I have have failed to update the dependency settings in sqflite). Try running `flutter pub upgrade`

**Comment by alextekartik** [comment]
One thing important is that application are typically re-signed by the playstore (unless you add your own keys). So you cannot test your schema upgrade from a development machine, as the playstore version and your development version have a different signature so Android Studio or flutter tools will delete the existing version if the signature is different. What I do typically is that I keep an apk of each version I published so that I can test migration in a real case scenario.

**Comment by daniel-hopkins** [comment]
I did _not_ know that. Perhaps that's my issue, but it's still strange that it works sometimes and not others.
I'll close this for now as it's likely not sqflite related. Thank you for your help!
