### ISSUE TITLE
Make sqflite cross tab/isolate safe

### ISSUE THREAD

**Issue by alextekartik** [tekartik/sqflite#886]
Current sqflite is not cross isolate and cross tab safe regarding transactions, i.e. if a call comes from another tab or isolate while a transaction is in progress, it is ran in the current running transaction which is wrong.
The work means first starting by adding a transactionId when beginning a transaction and queuing calls coming from other client or without a transaction.

**Comment by absar** [comment]
Good to know you already started working on it. While you are at it, would you provide some info on what happens in this scenario. Recently I came across an issue in production where App is updated but the DB got `database_closed 1` probably due to this the DB somehow updated to the new version but is missing new tables, and I couldn't 100% figure out what exactly happened, this is what I assume might have happened:

1. App was on DB version 2, then it received an update to v3
2. App is updated but user has not yet opened the app, which means the DB is not upgraded yet it is still at v2
3. The app also has some daily background jobs using workmanager, which also update data in the DB
4. Since Android doesn't always trigger the background jobs if user doesn't open the app frequently, however it does abruptly run all jobs immediately after user opens it after a long time, probably this is what happened, the background jobs ran in their own Isolate when user opened the app and exactly at the same time frontend also tried to open and upgrade the DB, then the backend got `database_closed 1`
5. However what I couldn't figure out why just the DB version is updated to v3 but the new tables are not created, as the upgrade happens in a `transaction` the full transaction should have completed or rolled back, as SQFlite is setting the version at the end of `SqfliteDatabaseMixin.doOpen` and I am not doing any exception handling in `onUpgrade`

Trying to create a reproducible scenario but so far haven't been able to

**Comment by alextekartik** [comment]
Thanks for the info @absar. That is definitely a case that is not handled well currently (and testing and reproducing is painful). I have yet to find a solution for this (and this issue is regarding dealing with a part of it).

Currently if you use `singleInstance: true` (which is the default), if one isolate closes the database, the other isolate will indeed failed with a `database_closed` problem that you are seeing. Also transactions are not safe (this is what this issue is about).

If you use `singleInstance: false` each isolate deals with sqflite in a separate thread, which in theory should be safer but it seems that you might have some lock issue if the two instances start a transaction and you might have no other choice than to try again later...in iOS, I think the background job might be killed and I'm not sure what would happen if we are in the middle of the transaction.

I'm not sure what I would recommend yet. If you keep `singleInstance: true` (my preference as it handles hot reload/hot restart), in your background isolate (workmanager) you could open the database (without onCreate/ononUpgrade) and for example do nothing if the version is not what you expect (i.e. the version is 2, don't run your background job yet, it will run later once the main isolate updates it and your job is triggered again). You should also not close the database in the background isolate in this case (and if that's ok in your scenario, don't close the database at all in your main isolate neither).

This is definitely a scenario that should be handled better, sorry for not having full solution yet but hopefully working on this issue should solve it (or at least provide a way to solve it). I have not tested this scenario enough as I managed to avoid it in my own applications. I will try to make more tests on this in the future.

**Comment by absar** [comment]
Thank you for the quick response and suggestions. I do use `singleInstance: true` in all places which are opening the DB, in fact using a single source code to open the DB, and not closing the DB at all, neither from background isolate nor in the main.
Looking forward to what you come up with in the OP. Will keep you posted if I am able to prepare some tests or a reproducible.

**Comment by alextekartik** [comment]
sqflite 2.2.0+2 should now be cross isolate safe. sqflite_common_ffi_web 0.3.1 should be cross-tab safe (when using a shared worker, i.e. not on android chrome which does not have support for it yet). The sqflite_common_ffi implementation is already cross isolate safe (although users might have to deal with lock issue - I might open a different issue for that).
