### ISSUE TITLE
Module 'FMDB' not found

### ISSUE THREAD

**Issue by xtuck** [tekartik/sqflite#908]
The latest version of 2.2.1, compilation failed on the ios platform，
error message: "Module 'FMDB' not found",
my ios project does not contain any swift code.

**Comment by xtuck** [comment]
sqflite: 2.2.0+3 is successed

**Comment by alextekartik** [comment]
Thanks for the report. I think it is due to the fix for #898 
Can try the trick `use_frameworks!` described here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#module-fmdb-not-found

to see if it works for you? Thanks

**Comment by xtuck** [comment]
it doesn't suit me
I think you can do like this

#if __has_include(<FMDB/FMDB.h>)
#import <FMDB/FMDB.h>
#else
@import FMDB;
#endif

**Comment by alextekartik** [comment]
We have tried many solutions like you propose but none work for issue #898 when you import FMDB as a module in XCode. I'm not sure why it does not suit you since `use_frameworks!` is now by default for new projects (i.e. this is only needed for older project). I'm not an iOS expert but does it work using the proposed fix ?

**Comment by xtuck** [comment]
In Objective-C project without swift, use_frameworks! is not default config

I simulate #898

I did this:
1. create new flutter-app project
2. dependencies: sqflite: 2.2.0+3  in pubspec.yaml
3. flutter pub upgrade
4. flutter run
5. open ios project and add Package Dependncies: FMDB
6. pod update
7. run app
It work successfully, there are no errors.

My test project: https://github.com/xtuck/test_sqflite_tc.git

![8c772263-7ba4-4202-9b22-445f307e550a](https://user-images.githubusercontent.com/10590452/205310925-e4e5a31b-2957-408a-92b4-bf59db142998.jpeg)

**Comment by xtuck** [comment]
flutter doctor
[✓] Flutter (Channel stable, 3.3.4, on macOS 13.0.1 22A400 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

other
pod --version : 1.11.3
ruby --version :  ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin22]

**Comment by xtuck** [comment]
My all projects are use Objective-C and without swift. and some projects had child target(extension),  and extension config(use_frameworks!) must be the same as main target. so i change all config to "use_frameworks!" is very difficult.

**Comment by alextekartik** [comment]
Thanks for taking the time to create a project. Too bad the test project for issue #898 is no longer available as it was definitely not working without moving to 2.2.1. As a side note, your project works fine with 2.2.1 too and has use_frameworks. Since that is the default now, you might consider using it. I'm very bad at iOS sorry and I cannot explain why it sometimes work.

I also took the time to create a project that fails using 2.2.0+3 but succeeds with 2.2.1. It is basically the sqflite example app with sqflite override where like you I added FMDB as a framework:
https://github.com/alextekartik/sqflite_issue_898_ios

**Comment by xtuck** [comment]
I tested successfully.
I modified  all class like this:

in header file (.h):
write @class FMResultSet;  before @interface
or  @class FMDatabaseQueue;  
or  @class FMDatabase;

in implement file (.m): 
#if __has_include(<fmdb/FMDB.h>)
#import <fmdb/FMDB.h>
#else
@import FMDB;
#endif

it can work and compatible the both scene

**Comment by alextekartik** [comment]
Since I'm not sure where to do the changes (which header and implementation file), can you create a PR?

**Comment by xtuck** [comment]
look look my pr: #910

**Comment by alextekartik** [comment]
Thanks!

**Comment by alextekartik** [comment]
version 2.2.2-1 (published as a dev version for now to allow additional tests). Sorry for being super conservative as iOS still gives me headaches and I don't want to break anything for other users. If all is good, I'll publish as stable by the end of next week.

Thanks again for reporting and proposing a fix and fixing it!

**Comment by xtuck** [comment]
OK, Thinks too!
