### ISSUE TITLE
support cross platform

### ISSUE THREAD

**Issue by muchirajunior** [tekartik/sqflite#948]

**Comment by alextekartik** [comment]
The compatibility story is a bit complicated as it also includes non flutter support. However you can look at [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) for cross platform solutions

**Comment by aytunch** [comment]
@alextekartik I was also confused with the web support for sqflite. I am getting these errors
`saveEvent: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)`
I want to know what is the preffered way to use `sqflite` in web? which version to use and how to handle code in a project aiming for iOS, Android and web? If you can clarify, that would be great :D

**Comment by alextekartik** [comment]
Web support is still marked as experimental (but I know some people use it in production).

If you have any existing iOS/Android application, one solution is to change the default database
factory:

```dart
import 'package:sqflite_common_ffi_web/sqflite_ffi_web.dart';
import 'package:sqflite/sqflite.dart';

var path = '/my/db/path';
if (kIsWeb) {
  // Change default factory on the web
  databaseFactory = databaseFactoryFfiWeb;
  path = 'my_web_web.db';
}

// open the database
var db = openDatabase(path);
```

Setup info here: 
https://github.com/tekartik/sqflite/blob/master/packages_web/sqflite_common_ffi_web/README.md

**Comment by alextekartik** [comment]
> when do we expect the merge of the two like its mentioned in the documentation for sqflite_ffi_common

Oups I don't know where I said that, I guess I should remove this for now!

Cross platform support is a bit weird, sorry about that. The `sqflite` package,
implemented as a "classic" flutter plugin supports only Android, iOS and MacOS.

Desktop support (Linux, Windows) is provided by the `sqflite_common_ffi` package.
It is a dart package so it also works on the dart VM (command line) so it is not
a flutter plugin. Its implementation uses ffi. This implementation can also
support Android, iOS and MacOS but it is not a flutter plugin.

Experimental web support is provided by the `sqflite_common_ffi_web` package.

> Is there a plan to publish a single federated package?

Not at this time. Some might prefer `sqflite_common_ffi` over `sqflite`. The first
giving you access to the latest sqlite3 version and the second giving a smaller binary size.
Some wants encryption support. It is hard to make the proper choice for everyone.

As a side note, I find it weird when creating a linux only flutter application, that
my app has to download the `win32` package. Currently there is no way to limit dependencies
to only the platform you are supporting. More dependencies means more chance to have breaking bugs 
that you cannot fix.

I would even be more inclined to publish a separate packages for each platform that people have to include
one by one for the platforms they want.

Also I'm a freelance developer, maintaining it in my free-time so I don't always have time and
the energy to support it (since 2017!) in the best way. Documentation is poor, I know. I'm not a native english speaker.
Sometimes issues like this one bring me the opportunity to improve the documentation so I will
likely copy this response to the documentation.
